### ISSUE TITLE
Is this plugin still in active development?

### ISSUE THREAD

**Issue by madrid1979** [xwp/stream#1001]
Would be nice to know if this is a dead project. Anyone? Bueller?

**Comment by greggh** [comment]
I came to ask the same question.

**Comment by lkraav** [comment]
It's been struggling for resources for a while. Not clear what can happen next, when.

**Comment by tyrann0us** [comment]
According to https://wordpress.org/support/topic/notice-undefined-index-ip_address-in-classes-class-log-php-on-line-204/#post-11536134, @lukecarbis, who made many commits, no longer works for @xwp.

**Comment by valendesigns** [comment]
We’re discussing how to best support the plugin internally. I’ll have an update on how we’re going to proceed this week. Sorry for any issues this may be causing.

**Comment by lkraav** [comment]
This plugin is good enough to try a paid business model again. I would subscribe for sure (already spending x thousand $ / year on plugin subscriptions).

Just without the cloud part, that was attempted last time.

**Comment by greggh** [comment]
I would definitely pay a yearly fee to make sure this stayed up to date.

**Comment by tyrann0us** [comment]
>[…] I’ll have an update on how we’re going to proceed this week. […]

@valendesigns, it's been a week. Do you have an update for us? Thanks!

**Comment by madrid1979** [comment]
Problems...

**Comment by valendesigns** [comment]
I haven't found a new internal owner for the project yet. However, I will attempt to fix a few of the more pressing bugs over the next week or so.

**Comment by greggh** [comment]
@valendesigns The fixes are awesome to hear. Has any thought been put into a paid model? This is one of those plugins that I just need working. I don't need much in the way of new features, or updates. Only bug fixes, compatibility fixes, and updates to keep up with WordPress's changing versions. So standard maintenance. I would pay for that.

**Comment by madrid1979** [comment]
As per @greggh, I would be 100% on-board with paying for this plugin to help keep active development going.

**Comment by teljair** [comment]
I would like to note that I've just heard about this plugin and would pay for it. Especially with the Slack integration.

**Comment by valendesigns** [comment]
Development has resumed. Plans to offer this as a product are being discussed and we will update the repo if there is any movement on that. Closing this issue for now.
