### ISSUE TITLE
Add filter for cron check

### ISSUE THREAD

**Issue by tareiking** [xwp/stream#1013]
We use WP Stream, but have replaced native WP Cron with [HM Cavalcade](https://github.com/humanmade/Cavalcade). Part of installing cavalcade is setting `DISABLE_WP_CRON` to false (and allow cavalcade to run cron in parallel instead.

However, the [cron check](https://github.com/xwp/stream/blob/dd2f5809236d4849967a8ad860548a45b981ba4f/includes/functions.php#L123) in stream doesn't allow us to override this setting.

While #959 makes sense for general usage, I'd like to suggest creating a new filter to override this setting and allow compatibility with Cavalcade or those who are using custom WP CRON dropins or setups.

**Comment by kasparsd** [comment]
Fixed in #1029.

**Comment by kasparsd** [comment]
Version 3.4.1 has been released.
