### ISSUE TITLE
Settings > Exclude - can't create rules

### ISSUE THREAD

**Issue by slaFFik** [xwp/stream#1032]
# Bug Report

## Expected Behavior

I want to be able to create a rule.

## Actual Behavior

When I click Add New Rule - no interface to add a rule. Instead the table gets a new "no rules" row.
Might be related to #1031 (on the same page).

## Screenshots

![Screen Recording 2019-08-01 at 12 14 22 38 AM](https://user-images.githubusercontent.com/282234/62248740-83215200-b3f1-11e9-99cf-7fd5454c6186.gif)

## System Information

- Stream plugin version: 3.4.1
- WordPress version: WPMS 5.2.2
- PHP version: 7.3
- Browser: Chrome 75
- Computer operating system: Windows 10 Pro

**Comment by kasparsd** [comment]
Thanks for reporting the issue @slaFFik!

Could you please try the `develop` branch now which includes the fix for removing the warnings. Maybe those warnings were messing with the JS required for adding the rows.

**Comment by kasparsd** [comment]
@slaFFik Could you please test with the latest version 3.4.2 which is now on WP.org?

**Comment by slaFFik** [comment]
@kasparsd 
I've tested 3.4.2 - no errors and I can finally create rules. Thank you!
