### ISSUE TITLE
IP addresses in exlude rules not saved correctly

### ISSUE THREAD

**Issue by tyrann0us** [xwp/stream#1035]
# Bug Report

## Expected Behavior

Exclude rules should be saved correctly, even if some of them do not contain IP addresses.

## Actual Behavior

If there are multiple exclude rules and some of them have no IP address(es) set, settings are not saved correctly. The set IP addresses are then assigned to the wrong authors or roles, because they are displayed one after the other, ignoring whether an IP address was set in the current row at all.

## Steps to Reproduce the Problem

1. Create multiple exclude rules
2. Set IP addresses only for some rules
3. Save settings

## Screenshots
Before save

![screenshot-blog bernina local-2019 09 24-13-45-49](https://user-images.githubusercontent.com/8144115/65509425-c0c2c880-ded2-11e9-88ff-ca69eb1463b5.png)

After save

![screenshot-blog bernina local-2019 09 24-13-46-38](https://user-images.githubusercontent.com/8144115/65509436-c91b0380-ded2-11e9-9602-b027162c56aa.png)

## System Information

- Stream plugin version: [`dev-fix/ip-address`](https://github.com/xwp/stream/tree/fix/ip-address)
- WordPress version: 4.9.11
- PHP version: 7.2.0
- Browser: Google Chrome 77.0
- Computer operating system: macOS Mojave

**Comment by kasparsd** [comment]
Thanks for the reporting the issue @tyrann0us!

I could replicate the issue and it's probably caused by the way the form uses non-indexed input field names `name[]` which fails when some of them have an empty value.

**Comment by kasparsd** [comment]
@tyrann0us Could you please test with the `fix/1035-exclude-rules-table` branch? You will probably need to run `npm run build` to re-build the minified JS files with the latest changes.
