### ISSUE TITLE
Composer packages still missing built assets

### ISSUE THREAD

**Issue by kasparsd** [xwp/stream#1073]
The Composer package [available on Packagist.org](https://packagist.org/packages/xwp/stream) syncs with this GitHub repository and it uses the default source zip bundle instead of our custom release package.

One solution is to use `wpackagist-plugin/stream` from the [WordPress packagist](https://wpackagist.org/search?q=stream).

Another solution is to introduce a custom distribution repository that contains just the built artifacts similar to how Yoast SEO [does it](https://github.com/Yoast/wordpress-seo/blob/d797de4dedef6f6ce48de9fcc85ca72953239ba8/scripts/deploy_to_dist.sh) with https://github.com/Yoast-dist/wordpress-seo/

**Comment by kopepasah** [comment]
So I researched and mulled this over, and while the above solutions are no doubt a pathway to allowing developers to consume Stream more easily through Composer, I feel an in-house and portable solution involving a custom Composer Plugin to control the download location could best solve this challenge. Essentially, the plugin will hook into the `pre-install` event and change the download url to the Github release location of the package zip.

**Comment by kasparsd** [comment]
@kopepasah The `pre-install` hook only fires on the root package so adding a `pre-install` hook won't do anything when this plugin is added as a dependency.

Overall, I think this is a low priority issue since most users can use the WPackagist repository https://wpackagist.org/search?q=stream to install the plugin with all assets built and prepared.

**Comment by kopepasah** [comment]
@kasparsd I was referring to the `pre-install` event from Composer, not the `pre-install` scripts in the `composer.json` config (hence the need for a Composer Plugin).

**Comment by kasparsd** [comment]
Would that require all users to adding that custom Composer plugin as a dependency? Are there examples of other projects using this or a similar approach?

**Comment by kopepasah** [comment]
Yes, it would require the installation of a separate package, much like requiring `composer/installers` when working with Packagist.

**Comment by kasparsd** [comment]
@kopepasah Just found this Composer plugin which seems to be doing something similar to what you were suggesting (if I'm understanding correctly) https://github.com/openeuropa/composer-artifacts

**Comment by kopepasah** [comment]
Oh, yes. Great discovery. I am not 100% sure if we can add that information to the "extras" section of this package or users have to add it to their package, but it is definitely worth a try.

Assigning to myself to give it a go. 👨🏻‍💻

**Comment by kopepasah** [comment]
@kasparsd after some initial testing today, I can confirm this works as advertised. The only caveat is the Composer JSON is required to be added to the project package (not the packages of the project). Very similar idea to what I had, but done (probably) a cleaner way. 

My recommendation is we add some documentation of how to install this plugin with Composer (either with WP Packagist or using this method to install for official releases), but other than that there seems little we can do in regards to forcing the install dist on external packages.

**Comment by kasparsd** [comment]
> My recommendation is we add some documentation of how to install this plugin with Composer.

That's a good idea. I feel like WPackagist.org is a great solution for adding this plugin to any WP project and it would be nice to document it in the readme somewhere.

The original issue is that we have this plugin listed on https://packagist.org/packages/xwp/stream and it would be nice to have it in a working state there, too.

**Comment by kopepasah** [comment]
@kasparsd I added an issue for adding documentation: #1133. As for the issue with Packagist, I think that will be solved in #1074, correct?
