### ISSUE TITLE
Support ignoring certain options or option keys

### ISSUE THREAD

**Issue by TimothyBJacobs** [xwp/stream#1078]
# Feature Request

Stream has a [concept of ignored options](https://github.com/xwp/stream/blob/88317c6149f9a75d53db95c2cf5f10654a4b5a71/connectors/class-connector-settings.php#L338) but the list of options to ignore is static.

Some options are updated frequently by an automated fashion, not in response to a user action. This can lead to cluttered stream logs that aren't relevant to the end user.

It'd be helpful if a developer could exclude those options from being logged by stream. I think a filter on the `$ignored` array in both `is_key_ignored` and `is_option_ignored` would work well.

**Comment by lkraav** [comment]
As I just disabled `settings` connector completely exactly for "too much noise" reason, I think this issue is very relevant.

Filtering the key list makes perfect sense.

**Comment by kasparsd** [comment]
This is a great idea @TimothyBJacobs!

How about a filter on the output of `is_option_ignored()`:

```php
return apply_filters(
	'wp_stream_ is_option_ignored',
	in_array( $option_name, $ignored, true ),
	$option_name
);
```

**Comment by TimothyBJacobs** [comment]
That’d work great!

**Comment by kopepasah** [comment]
@kasparsd it might make more sense to just filter the static array:

```php
$ignored = apply_filters(
	'wp_stream_ignored_options',
	array(
		'image_default_link_type',
		'medium_large_size_w',
		'medium_large_size_h',
	)
);
```

**Comment by lkraav** [comment]
What are y'all thoughts on blocklist vs allowlist here?

Options are a massive noise problem, because there's so many different keys.

Perhaps site operators would only want to monitor a system-critical, and/or site-specific option key set.

Doesn't have to be part of this issue's solution, but throwing it out there before I forget.

**Comment by kopepasah** [comment]
@lkraav now that you mention it, I think the idea of an allow/disallow would be most beneficial and Kaspar's suggestion would cover that functionality as well.

**Comment by kopepasah** [comment]
I pushed up a change which filters the return value `is_option_ignored()`. This change will allow easily creating lists of allow/disallow options. 

Side note, options can be completely turned off and on by using either of these (respectively):
```php
add_filter( 'wp_stream_is_option_ignored', '__return_false' );
```
or
```php
add_filter( 'wp_stream_is_option_ignored', '__return_true' );
```
