### ISSUE TITLE
3.4.3: debounce AJAX select elements, avoid server overload - followup #1052

### ISSUE THREAD

**Issue by lkraav** [xwp/stream#1081]
Followup to #1052

# Bug Report

One AJAX request is triggered for every keypress on Users dropdown.

My platform site currently has 15000 users, this is a real query bomb if you type a whole e-mail in there to try to narrow it down.

## Expected Behavior

Select element should only trigger query after probably 0.5s has passed after last keystroke.

## Steps to Reproduce the Problem

1. Open Network panel

2. Type into Users filter select element

3. Observe network request triggered for each keystroke

**Comment by kasparsd** [comment]
Is the input field using the select2 input wrapper? I wonder if they provide throttling out of the box for this and we just haven't enabled it.

**Comment by lkraav** [comment]
Yep, it's Select2. And this is what we did in Sensei https://github.com/Automattic/sensei/pull/2282/files super simple.

**Comment by oscarssanchez** [comment]
Hi there, I can confirm this takes down a site with 30k users. Solution proposed by @lkraav works for me.
