### ISSUE TITLE
Provide a filter in Connector_Posts to handle $summary for the custom post statuses.

### ISSUE THREAD

**Issue by Nikschavan** [xwp/stream#1085]
Delete the section that is not applicable:

### Feature Request

By default for any custom post status changes, a default message is added which does not describe the actual change that was made, with a filter, we can manage custom messages to handle post-status changes.

https://github.com/xwp/stream/blob/33dcfa86932bffdc11cbf3ade3da73a38cd4818e/connectors/class-connector-posts.php#L242-L246

**Comment by kopepasah** [comment]
Hey @Nikschavan! Thanks so much for the suggestion. 

Actually, I think what you want to do is already possible via the `wp_stream_log_data` filter found [here](https://github.com/xwp/stream/blob/master/classes/class-connector.php#L112).

Something like this, for example, would set a message status when a status has been updated:

```php
add_filter( 'wp_stream_log_data', function( $data ) {
	if (
		'update' === $data['action'] &&
		! empty( $data['args'] ) &&
		! empty( $data['args']['new_status'] ) &&
		! empty( $data['args']['old_status'] )
	) {
		$data['message'] = 'Post status updated from ' . $data['args']['old_status'] . ' to ' . $data['args']['new_status'];
	}

	return $data;
} );
```

Let me know if this does not solve your issue.

**Comment by lkraav** [comment]
Sure, but wouldn't everybody (those that care about post status changes) want this?

**Comment by kopepasah** [comment]
@lkraav are you recommending that we need to add the status changes to the log by default? If so, I feel that would need a separate issue for discussion.

**Comment by kasparsd** [comment]
Yeah, let's close this out as there is a way to "manage custom messages to handle post-status changes" per the original request using the filter example that @kopepasah provided, and create a new issue for the feature request -- the post status change log sounds like a great feature!

@kopepasah Do you agree? If so, could you please create a new ticket for that?

**Comment by kopepasah** [comment]
@kasparsd yeah, I totally agree that the post log information should include the post status to which it was changed. I've created a new feature request for this: #1132 and closing out this task.
