### ISSUE TITLE
Incorrect Date and Time

### ISSUE THREAD

**Issue by kasparsd** [xwp/stream#1091]
See https://wordpress.org/support/topic/incorrect-date-and-time/

> I’m having an issue with the plugin, that the date and time for all records is being set as
> 10 years ago
> -0001/11/30
> 12:00:00 AM

**Comment by kasparsd** [comment]
This is still happening per reports here https://wordpress.org/support/topic/incorrect-date-and-time/ so I'm reopening the issue.

**Comment by gagan0123** [comment]
Thanks guys, the recent patch works perfectly. Tested with a few of the sites I manage on different servers. Awaiting updated version to show up, to update on all sites.

I was wondering, why a new function was written to provide the date(as in previous resolution), when one already exists and works perfectly in WordPress itself. In coding LESS = MORE.
