### ISSUE TITLE
Improve Test Coverage

### ISSUE THREAD

**Issue by kidunot89** [xwp/stream#1093]
# Feature Request

The alert and connector class have little to now coverage.
- Alert types
  - ![image](https://user-images.githubusercontent.com/13604318/83191700-6f727500-a102-11ea-817c-8d49201aa386.png)
- Connectors
  - ![image](https://user-images.githubusercontent.com/13604318/83191612-510c7980-a102-11ea-96bd-afdc5d7b76bb.png)

The plugin core classes have better coverage, but still aren't that good.
![image](https://user-images.githubusercontent.com/13604318/83191992-e445af00-a102-11ea-9ebb-21db01cb0fd7.png)
_(Sorry about the artifact :man_facepalming:)_

**Comment by kasparsd** [comment]
@kidunot89 Would you like to keep this issue open until we're reached a certain test coverage range? Or can we close it in favour of individual tickets for specific parts of code?

**Comment by kidunot89** [comment]
@kasparsd Let's leave this open until Code coverage is at an acceptable level. I also want to discuss what to do about parts of the code where simulation isn't really an option, like WP core update logging functionality.

**Comment by kasparsd** [comment]
Looks like this keeps getting closed because of the `Fixes #....` references in the pull requests @kidunot89 :)

**Comment by kidunot89** [comment]
:man_facepalming:
