### ISSUE TITLE
Support for Advanced Custom Fields (ACF) version 5

### ISSUE THREAD

**Issue by kasparsd** [xwp/stream#1122]
> When updating an ACF repeater field (which is inside an ACF Group field),
the Stream plugin crashes as the mysql escape function from WP_DB gets incorrect parameters passed.

https://wordpress.org/support/topic/error-crash-when-updating-acf-repeater-field/

**Comment by kasparsd** [comment]
@kidunot89 Would #1118 fix this too?

**Comment by kidunot89** [comment]
@kasparsd No, I wasn't even aware of this issue, but it does coincide with the purpose for the PR so I'll patch it in that PR.

**Comment by strarsis** [comment]
Has this been fixed now? I want to re-enable stream on that site but I don'T want to trigger these ACF related errors again.

**Comment by kidunot89** [comment]
@strarsis It should be resolved. Feel free to post here is the issue still persists and I'll reopen this.
