### ISSUE TITLE
Stream Records dates are 2052 years ago with zeroed 'created' fields in database

### ISSUE THREAD

**Issue by suderman** [xwp/stream#1140]
# Bug Report

The dates all display as:

```
2052 years ago
-0001/11/30
12:00:00 AM
```

And also, in the database, the created field in wp_stream are all zeroes.

## Screenshots

![IMG_3659](https://user-images.githubusercontent.com/12491/87193500-1166af00-c2b6-11ea-992a-99154196b2ef.jpeg)

![IMG_3660](https://user-images.githubusercontent.com/12491/87196123-1ed06900-c2b7-11ea-86b7-7ea855d0f62e.jpeg)

Drag and drop screenshots in this area that help illustrate the problem.

## System Information

- Stream plugin version: 3.5.0
- WordPress version: 5.4.2
- PHP version: 7.4
- Browser: iPadOS Safari
- I also use MySQL 8 on DigitalOcean's managed database service

**Comment by kasparsd** [comment]
Thank you for opening the issue @suderman! This appears to be the same issue as #1091 so I'll close this for now. Please do let us know if you think this should be a separate issue.
