### ISSUE TITLE
Stop Excluding Tests from Coding Standards

### ISSUE THREAD

**Issue by kopepasah** [xwp/stream#1146]
# Feature Request

Currently, tests are excluded from the coding standards check: https://github.com/xwp/stream/blob/develop/phpcs.xml.dist#L25

As more tests are being written, we either should not exclude these from this check or create a check to ensure standards are followed in tests as well.

**Comment by kopepasah** [comment]
Specifically relates to #1118, in regards to shorthand vs long form array syntax: https://github.com/xwp/stream/pull/1118#discussion_r458374497

**Comment by kopepasah** [comment]
Just adding a note here that I am currently working through adding this functionality, including ensuring current tests meet standards.

**Comment by delawski** [comment]
This has been done in the [4.0.1 release](https://github.com/xwp/stream/releases/tag/v4.0.1).
