### ISSUE TITLE
Site deletion isn't logged

### ISSUE THREAD

**Issue by johnbillion** [xwp/stream#1175]
# Bug Report

## Expected Behavior

When a site gets deleted from a Multisite network, the actual site deletion isn't logged in Stream. Several related records are logged instead.

## Actual Behavior

When a site gets deleted, Stream logs a record for every user who gets removed from the site, and logs a record that the "Blog Count" setting was updated, but there's no record of the site being deleted.

## Steps to Reproduce the Problem

1. From the Network Admin -> Sites screen, click the `Delete` action link for a site
2. Confirm your action
3. View the Stream logs for the network

I think the preference here would be for a single "Site Deleted" log to be recorded in place of all the logs that are recorded for each user on the site being removed from it. If a site with 100 users gets deleted, you have 101 records creating unnecessary noise.

## Screenshots

![](https://user-images.githubusercontent.com/208434/93586623-7a4a6180-f9a0-11ea-8ee7-797a5f76d0ae.png)

**Comment by eltonmorais** [comment]
Update it's also not working

**Comment by kidunot89** [comment]
@eltonmorais The solution has been merged yet. Sorry :disappointed:.
