### ISSUE TITLE
Stream doesn't detect programmatically created posts correctly

### ISSUE THREAD

**Issue by dero** [xwp/stream#1176]
# Bug Report

The Posts connector uses the `transition_post_status` hook to detect posts being updated and created. It only considers the post being created [when it transitions from `auto-draft` to anything else](https://github.com/xwp/stream/blob/b540f51a530f82e2586d7b16180fd5024bc5b826/connectors/class-connector-posts.php#L258-L260).

This is likely enough to capture posts being created in WordPress admin. However, calling `wp_insert_post` programmatically will assign a `new` status to posts created via other means. Those posts are then reported as `updated`.

More context: https://github.com/xwp/stream/pull/1121#discussion_r488044973

## Expected Behavior

Stream should report programmatically created posts as `created`.

**Comment by kidunot89** [comment]
I don't know if I would consider this a bug, but a design choice. I'm pretty sure the logic here was also written with the belief that `draft` was the default post status. I also believe we can resolve this by changing this conditional [here](https://github.com/kidunot89/stream/blob/tests/posts-connector/connectors/class-connector-posts.php#L199)

**Comment by dero** [comment]
> I don't know if I would consider this a bug, but a design choice.

@kidunot89 I don't follow, _what_ exactly is a design choice? Note: `draft` is not the same as `auto-draft`.

Let me explain why I consider this a bug.

The `$action` is either `created` or `updated` and, straightforwardly, those values should correspond to situations where a new post is created vs. when an existing post is updated. However, using `wp_insert_post` programmatically to create new post will incorrectly lead to Stream logging that a post has been `updated`.

The reason for [the `created` condition in Stream](https://github.com/kidunot89/stream/blob/c1622e9435306a0b8de9836c565eb9ccdab8c1f9/connectors/class-connector-posts.php#L258) is how WordPress creates new posts in the Admin. It will create an `auto-draft` post in the DB when "New Post" is clicked in the admin (see [here](https://github.com/WordPress/wordpress-develop/blob/8b9823f53621a63d0a47626920f6930f35db160c/src/wp-admin/post-new.php#L66) and [here](https://github.com/WordPress/wordpress-develop/blob/dd076bb61106e56404c4980d25e7d22906e2398f/src/wp-admin/includes/post.php#L687)).

However, posts created via other means will likely transition from status `new` to their final status directly. Stream doesn't account for the `new` status in the callback logic at all. I can imagine two design decisions being made here:

1. Do not log programmatically created posts.
2. Log programmatically created posts.

The first option would skip logging any posts that transition from the `new` status, the second option would set `$action` to `created` for posts _created_ this way. Is this line of thought incorrect?

> I also believe we can resolve this by changing this conditional here to something like this

That doesn't address the issue as it would still lead to `$action` being set to `updated`.

**Comment by dero** [comment]
Fixed by #1121 -- closing.
