### ISSUE TITLE
siteurl on integration data for Site create/update/delete

### ISSUE THREAD

**Issue by eltonmorais** [xwp/stream#1187]
# Feature Request

On Sites log and data should have the siteurl. My use case, for example, I use that to dinamically create an register on Cloudflare with the subdomain. But the subdomain are not sent on the integration with my webhook (I used Slack option as webhook).

For solve my problem now I created a fork replacing sitename to siteurl, that's it's more usefull to me.

## System Information

- Stream plugin version: 3.5.1
- WordPress version: 5.5.1
- PHP version: 7.4
- Browser: Chrome
- Computer operating system: Windows

**Comment by kidunot89** [comment]
@eltonmorais I've added implemented this in an existing PR :point_up: 

The blog `name`, `url` and `id` have been added to the log meta. Feel free to pull down the branch in the PR and confirm your issue is resolved. Please leave any comments can be left in PR?
