### ISSUE TITLE
Warning PHP 8 support

### ISSUE THREAD

**Issue by thefrosty** [xwp/stream#1202]
# Bug Report

```
Warning: WP_Stream\DB::WP_Stream\{closure}(): Argument #2 ($key) must be passed by reference, value given in /../plugins/stream/classes/class-db.php on line 64
```

## System Information

- Stream plugin version: latest
- WordPress version: 5.5.3
- PHP version: 8.0

**Comment by kasparsd** [comment]
Thanks for reporting this @thefrosty!

**Comment by Nikschavan** [comment]
There is also one more deprecation notice being thrown on PHP 8 - 

```
PHP Deprecated:  Required parameter $alert follows optional parameter $context in stream/alerts/class-alert-trigger-author.php on line 161
```

**Comment by kasparsd** [comment]
Create #1278 to cover dev tooling update since that is a bit harder to fix due to dependency issues.
