### ISSUE TITLE
Compatibility with WP Graphql

### ISSUE THREAD

**Issue by sagararyal** [xwp/stream#1239]
# Bug Report

Activating Stream Crashes WP GraphQL (not sure if the issue is with Stream or WP GraphQL, but WP points to the file below)
Loading siteurl/graphql
 
results to:
<img width="862" alt="Screen Shot 2021-03-03 at 10 46 42 PM" src="https://user-images.githubusercontent.com/5401575/109878681-e251e300-7c74-11eb-805a-b5444e2aba15.png">

## System Information

- Stream plugin version: Version 3.6.2
- WP GraphQL: Version 1.2.5
- WP GraphQL WPML : Version 0.0.1
- WordPress version: 5.6.2 
- PHP version: 7.4
- Browser: Any
- Computer operating system: Any

**Comment by kidunot89** [comment]
@sagararyal Sorry for the late response. Are you using any other plugins or have some Alerts set to trigger?

**Comment by sagararyal** [comment]
@kidunot89 Just activating stream creates the issue. No alerts set.

I have WPML, ACF; and Cloudflare; but I also have another identical site with same set of plugins excluding GraphQL; where stream works perfectly.

**Comment by kidunot89** [comment]
@sagararyal Can you test you setup against the branch in ☝🏿 PR #1243

**Comment by sagararyal** [comment]
Just ran some more tests:

The issue could also be related to:
https://github.com/rburgst/wp-graphql-wpml
