### ISSUE TITLE
PHP 8 - PHP Deprecated:  Required parameter $alert follows optional parameter $context

### ISSUE THREAD

**Issue by cjhaas** [xwp/stream#1272]
# Bug Report

PHP 8 is deprecating required function/method parameters following optional parameters. The `Alert_Trigger` abstract class and all four child classes violate this by this signature:

```php
public function get_display_value( $context = 'normal', $alert ){}
```

Which raises warnings such as:

```
PHP Deprecated:  Required parameter $alert follows optional parameter $context in stream/alerts/class-alert-trigger-author.php on line 161
```

This was mentioned in a comment attached to #1202 but I thought it would be best to have a dedicated ticket since this is pretty easy to fix.

**Comment by kasparsd** [comment]
Thanks for the detailed issue and the matching pull request @cjhaas!
