### ISSUE TITLE
[PHP 8] Error when updating widgets.

### ISSUE THREAD

**Issue by itsTheFae** [xwp/stream#1294]
# Bug Report
While Stream is active on PHP 8 host, adding or removing widgets in WordPress causes an error to be thrown.  The named arguments added to PHP 8 create an issue with the call chain found at: `/stream/connectors/class-connector-widgets.php` lines 300, 301, as well as 360 and 361

## Expected Behavior
The expected behavior is simply saving the widgets without delay or error messages.

## Actual Behavior
When saving, update may take a moment and then report there was an error via pop-up at the bottom of the screen, which you can easily glance over if you're scrolling about.   
If you have logging enabled, you will find the following message:  
`PHP Fatal error:  Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /var/www/dcr/wp-content/plugins/stream/connectors/class-connector-widgets.php:300`

## Steps to Reproduce the Problem

1. Use PHP 8 with latest WordPress 5.8.1
2. Install latest Stream plugin
3. Create a couple widgets and then delete one to trigger the functions.
4. Check your error logging for details.

## System Information

- Stream plugin version: 3.8.1
- WordPress version: 5.8.1
- PHP version: 8.0.11

## Possible Solution

If you're using PHP 8, you can patch the error-prone lines by adding the parameter names to `call_user_func_array` so that lines 300, 301, as well as 360 and 361 look like this:
```php
$all_old_widget_ids = array_unique( call_user_func_array( callback:'array_merge', args:$old ) );
$all_new_widget_ids = array_unique( call_user_func_array( callback:'array_merge', args:$new ) );
```
The issue with this patch is that it clearly is not syntactically compatible with any previous version of PHP.  I'm sure there is a more compatible way to patch this, I just don't have the time to figure it out at the moment.

**Comment by itsTheFae** [comment]
`call_user_func_array` is at least faster than doing a manual loop.  Unpack via `...` isn't available until 5.6 which I guess we can assume no one uses php older than that and use something like `array_unique(array_merge(...array_values($old)));` instead.

**Comment by anthonyeden** [comment]
Any progress here? This is blocking my migration of a fair few sites to PHP8.

**Comment by vishaldabhade** [comment]
I am facing the same issue while updating a new widget. It gives a 500 error. Is there any way to resolve this?

**Comment by itsTheFae** [comment]
@kasparsd What can I do to help patch this bug?  Shall I fork and make a PR for one of the changes I've mentioned in this issue?  Which method would you prefer? 

I unfortunately don't have time to figure out what rational was behind the original choice of calls.  WordPress core made use of this pattern, so the easy guess is someone else just borrowed that method when looking for ways to interact with the array of widget data.  While I've been using WordPress for some years, I don't have expert input on their data structures and design choices.  
It's been a few months since I opened the issue, and having moved across the states since then I'll have to dig back into the code and various docs to see if my previous patches are (still) sane.   
So far, the patch is working without issue for me.   Are there a battery of tests I can run against these changes?

I look forward to getting a patch done so we can use this plugin with WordPress and PHP 8.

Thanks for your time.

**Comment by kasparsd** [comment]
Version [3.9.1](https://github.com/xwp/stream/releases/tag/3.9.1) should be out on WP.org in a few minutes which includes this fix!
