### ISSUE TITLE
Notice in admin dashboard on WP trunk

### ISSUE THREAD

**Issue by ryelle** [xwp/stream#1308]
Activating Stream on WP trunk (WordPress 6.0-alpha-52609) triggers a notice via `_doing_it_wrong`:

> Notice: Function add_menu_page was called incorrectly. The seventh parameter passed to add_menu_page() should be an integer representing menu position. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 6.0.0.) in /var/www/html/wp-includes/functions.php on line 5768

The menu position is set here:

https://github.com/xwp/stream/blob/489fb8777047f6c61599e16ba28c375263602a27/classes/class-admin.php#L321-L328

but the comment about decimal points to avoid collisions is [not true anymore](https://core.trac.wordpress.org/ticket/23316).

## System Information

- Stream plugin version: 3.8.2
- WordPress version: 6.0-alpha-52609

**Comment by delawski** [comment]
I was not able to replicate this issue.

It looks like the original suggestion to allow only integers has been turn down eventually for the 6.0.0 release:

https://github.com/WordPress/wordpress-develop/commit/4f290ecd64e0e30bb52bbaf63446254e68e577f3

The [docs](https://developer.wordpress.org/reference/functions/add_menu_page/#parameters) state that `$position` can be `int|float`.

I'm closing this one.
