### ISSUE TITLE
PHP 8.1: PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by thefrosty** [xwp/stream#1349]
# Bug Report

## Expected Behavior

No error message.

## Actual Behavior

```
PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/local/wordpress/wp-content/plugins/stream/classes/class-log.php on line 215
```

## Steps to Reproduce the Problem

1. Just logging in and traversing core admin pages.

## System Information

- Stream plugin version: 3.9.0
- WordPress version: 6.0
- PHP version: 8.1

**Comment by justinmaurerdotdev** [comment]
Bumping this issue because it was not, in fact, fixed by the previous merges. But, my most recent PR should fix this.
