### ISSUE TITLE
Feature Request: Button to generate a CSV Export/Download of current filtered view of data

### ISSUE THREAD

**Issue by bemdesign-er** [xwp/stream#1383]
# Feature Request

It would be very useful to have a button titled "CSV Export" that users could click to generate a CSV export of the data of the current filtered view for download. This would allow users to provide activity audit reports to website stakeholders without having to setup WordPress website accounts and change access permissions on the Stream plugin. It would also allow users to save simple CSV archives of data in case there is a need for a forensic audit after the log timeframe set in Stream.

**Comment by johnbillion** [comment]
This already exists as a "Record Actions" control at the bottom of the screen. You can download a CSV or a JSON file.
