### ISSUE TITLE
CSV export is malformed when any value contains a comma

### ISSUE THREAD

**Issue by johnbillion** [xwp/stream#1416]
# Bug Report

## Expected Behavior

When exporting logs as a CSV, all data should be well-formed.

## Actual Behavior

When any field value contains a comma, the CSV is malformed.

## Steps to Reproduce the Problem

1. Set your user display name to one that contains a comma, for example "Last Name, First Name"
2. Perform an action that gets logged in the audit log
3. Visit the audit log screen and download a CSV from the Record Actions menu at the bottom
4. Open the CSV in a spreadsheet application which will show the data in columns
5. Observe that the CSV output for the affected row is malformed due to the unquoted comma

## Suggested Fix

The `Exporter_CSV::output_file()` method should use `fputcsv()` instead of manually concatenating fields with commas.

## System Information

- Stream plugin version: 3.9.2
- WordPress version: 6.1
- PHP version: 8.0

**Comment by bemdesign-er** [comment]
It appears this issue has returned - we noticed it when updating plugins that have commas or media files with commas in their names. When we export activity logs as a CSV file for the month, these items are split into columns based on where the comma was located in the plugin/file name, creating a bit of a messed up CSV.
Issue occurs with Stream 4.0.2 running on WordPress 6.6.2.
