### ISSUE TITLE
3.10.0 missing from Packagist

### ISSUE THREAD

**Issue by rmccue** [xwp/stream#1467]
# Bug Report

## Expected Behavior

3.10.0 should be listed [on Packagist](https://packagist.org/packages/xwp/stream) since it [has been tagged](https://github.com/xwp/stream/releases/tag/3.10.0)

## Actual Behavior

Sadly, it is missing.

## Steps to Reproduce the Problem

1. [Look at Packagist](https://packagist.org/packages/xwp/stream)
2. Observe lack of 3.10.0
3. Cry (optional)

## Screenshots

![Screenshot 2023-11-13 at 17 53 02](https://github.com/xwp/stream/assets/21655/d4ad277a-6f6c-4c94-a9aa-52028cac988a)

## System Information

- Stream plugin version: Not 3.10.0
- WordPress version: Any
- PHP version: Any
- Browser: Any
- Computer operating system: Any

**Comment by kasparsd** [comment]
Indeed, the distribution repo doesn't have it https://github.com/xwp/stream-dist -- sorry about confusion!

Looks like the CI build for that specific tag was cancelled https://app.travis-ci.com/github/xwp/stream/jobs/611248230

**Comment by rmccue** [comment]
Ah, intriguing - can we get that rebuilt? :D

**Comment by kasparsd** [comment]
This is now done https://github.com/xwp/stream-dist/releases/tag/3.10.0 and the release is also available from Packagist.
