### ISSUE TITLE
Dynamic callback function name cannot include hyphens

### ISSUE THREAD

**Issue by shadi-sharaf-nuk** [xwp/stream#1468]
# Bug Report

Dynamic callback methods in custom connectors, eg: `callback_ACTION_NAME` cannot have hyphens in their method name, however the callback discovery routine does not convert hyphens to an underscore, hence connectors cannot target actions with hyphens like `load-xxx_xxx` unless they override the `callback` method and target the action manually.

## Expected Behavior

For an action like `load-something`, I should be able to use `callback_load_something` to log that action.

## Actual Behavior

I can't use a dynamic callback to target that action, only way is to override the `callback` method.

## System Information

- Stream plugin version: ALL, including current 3.10.0
- WordPress version: ANY
- PHP version: ANY
- Browser: ANY
- Computer operating system: ANY

**Comment by shadi-sharaf-nuk** [comment]
Hey @schlessera @kasparsd, trying to issue a PR against this issue, but seems like external contributions might be disabled?

<img width="504" alt="image" src="https://github.com/xwp/stream/assets/129750337/1e5000d9-7514-4f5c-8b83-a638889708d3">

**Comment by kasparsd** [comment]
@shadi-sharaf-nuk Can you please link to the branch you're creating the pull request from? I'm seeing external pull request being created very recently such as #1462.

**Comment by kasparsd** [comment]
Interesting. This is what I'm seeing -- looks like it would allow me to create a pull request:

<img width="934" alt="pr" src="https://github.com/xwp/stream/assets/169055/b3b2e2a9-4eb9-4659-a1c0-325081d252e6">

Can you please share what you are seeing?

**Comment by shadi-sharaf-nuk** [comment]
I'm seeing the same as you, but when I submit, I see the error I attached above 🤷 

Unsure if this is related to me being a previous contributor maybe?

**Comment by shadyvb** [comment]
My bad, I stupidly was trying to create the PR from another GitHub account who doesn't have access to my fork 🤦 Sorry for the confusion.
