### ISSUE TITLE
Uncaught ValueError: Unknown format specifier "!"

### ISSUE THREAD

**Issue by mesiarm** [xwp/stream#1489]
# Bug Report

## Expected Behavior

Logging record on post update

## Actual Behavior

Got:
Uncaught ValueError: Unknown format specifier "!" in /opt/www/html/wp-content/plugins/stream/classes/class-log.php:127
Stack trace:
#0 /opt/www/html/wp-content/plugins/stream/classes/class-log.php(127): vsprintf()
#1 [internal function]: WP_Stream\Log->log()
#2 /opt/www/html/wp-content/plugins/stream/classes/class-connector.php(178): call_user_func_array()
#3 /opt/www/html/wp-content/plugins/stream/connectors/class-connector-wordpress-seo.php(433): WP_Stream\Connector->log()
#4 /opt/www/html/wp-content/plugins/stream/connectors/class-connector-wordpress-seo.php(353): WP_Stream\Connector_WordPress_SEO->meta()
#5 [internal function]: WP_Stream\Connector_WordPress_SEO->callback_added_post_meta()
#6 /opt/www/html/wp-content/plugins/stream/classes/class-connector.php(127): call_user_func_array()
#7 /opt/www/html/wp-includes/class-wp-hook.php(324): WP_Stream\Connector->callback()
#8 /opt/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#9 /opt/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#10 /opt/www/html/wp-includes/meta.php(156): do_action()
#11 /opt/www/html/wp-includes/meta.php(252): add_metadata()
#12 /opt/www/html/wp-includes/post.php(2626): update_metadata()
#13 /opt/www/html/wp-content/plugins/wordpress-seo/inc/class-wpseo-meta.php(717): update_post_meta()
#14 /opt/www/html/wp-content/plugins/wordpress-seo/admin/metabox/class-metabox.php(805): WPSEO_Meta::set_value()
#15 /opt/www/html/wp-includes/class-wp-hook.php(326): WPSEO_Metabox->save_postdata()
#16 /opt/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#17 /opt/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#18 /opt/www/html/wp-includes/post.php(4839): do_action()
#19 /opt/www/html/wp-includes/post.php(4930): wp_insert_post()
#20 /opt/www/html/wp-admin/includes/post.php(453): wp_update_post()
#21 /opt/www/html/wp-admin/includes/post.php(2085): edit_post()
#22 /opt/www/html/wp-admin/post.php(336): post_preview()
#23 {main}
  thrown

## Steps to Reproduce the Problem

1. Update wp post

## Screenshots

Drag and drop screenshots in this area that help illustrate the problem.

## System Information

- Stream plugin version: 4.0.0
- WordPress version: 6.5.4
- PHP version: 8.1.2
- Browser: Chrome
- Computer operating system: Ubuntu 18.04

**Comment by tharsheblows** [comment]
Support forum issues:
https://wordpress.org/support/topic/fatal-error-unknown-format-specifier-2/
https://wordpress.org/support/topic/fatal-error-when-saving-the-seo-title-meta-with-in-the-post-title/

**Comment by krokodok** [comment]
FYI: I have to PRs open for these errors.

https://github.com/xwp/stream/pull/1485
https://github.com/xwp/stream/pull/1486

**Comment by tharsheblows** [comment]
@krokodok Thank you! I think that's the right approach although I have a request in regards to what you said:

> Yes, there is no real consistency in these connectors. But preventing fatal errors seems still necessary with some hot fixes, so that users won't get fatal errors.

Because there's no real consistency, could you add a method to the abstract class `Connector` like `escape_messages( $message )` (or a better name!) which returns the value with the added %? Then use that where necessary. 

That way it's easier to discover and document, especially when we go to [document how to create new Connectors](https://github.com/xwp/stream/issues/1500).

And also add a test of the method to the `Test_Connector` class. (I wrote a test for the Yoast connector so if you don't want to do that one, I'll add it in later.)

**Comment by krokodok** [comment]
@tharsheblows Good feedback! I don't have a lot of time for open source commitments right now, so feel free to take this on if you have some time on your hands.

**Comment by tharsheblows** [comment]
@krokodok Thank you! I can do that 😊
