### ISSUE TITLE
Add documentation on how to create new connectors

### ISSUE THREAD

**Issue by tharsheblows** [xwp/stream#1500]
# Feature Request

Add documentation on how to create new connectors for plugin authors and developers.

Support forum links:
- https://wordpress.org/support/topic/feature-compatibility-with-polylang-pro/
- https://wordpress.org/support/topic/support-maipoet-plugin/
- https://wordpress.org/support/topic/add-support-for-sensei-plugin/

**Comment by delawski** [comment]
Related: #819

**Comment by delawski** [comment]
It looks like we already have a quite comprehensive documentation on how to create custom connectors in the wiki:

https://github.com/xwp/stream/wiki/Creating-a-Custom-Connector

**Comment by delawski** [comment]
I have updated the https://github.com/xwp/stream/wiki/Creating-a-Custom-Connector page contents with a further polished (thanks to GPT) connector example.
