### ISSUE TITLE
Changes made in the Customizer are not being logged

### ISSUE THREAD

**Issue by fjarrett** [xwp/stream#308]
After clicking **Save & Publish** in the Customizer no records are being logged by Stream for changes that were performed.

![screen shot 2014-03-07 at 8 59 24 pm](https://f.cloud.github.com/assets/522158/2364355/b1dc8d54-a66d-11e3-962d-02a0949bd923.png)

We'll need to improve the following connectors so that these changes are always tracked:

- [x]  Widgets (#391)
- [ ] Menus
- [ ] Settings

/cc @westonruter

**Comment by lukecarbis** [comment]
@westonruter This thread is pretty old, but it's still an issue.

Would you have time to look into this? Or could you recommend a place to start?

**Comment by westonruter** [comment]
@lukecarbis hey, I don't have time to look into it, but I do have a recommended starting place:

The [`customize_save_{$id_base}` action](https://github.com/xwp/wordpress-develop/blob/master/src/wp-includes/class-wp-customize-setting.php#L232-L259) fires for each setting that gets saved. It's unfortunate actually that the action has this dynamic portion, but what you can do is hook into the global [`customize_save` action](https://github.com/xwp/wordpress-develop/blob/master/src/wp-includes/class-wp-customize-manager.php#L788-L796) which actually should be called `customize_save_before`, and you can then iterate over all of the settings to add the necessary actions for Stream. For instance:

```php
<?php
add_action( 'customize_save', function ( \WP_Customize_Manager $wp_customize ) {

	$actions_added = array();

	foreach ( $wp_customize->settings() as $setting ) {
		/** @var \WP_Customize_Setting $setting */
		$id_base = strtok( $setting->id, '[' );
		if ( isset( $actions_added[ $id_base ] ) ) {
			continue;
		}

		add_action( "customize_save_{$id_base}", function( \WP_Customize_Setting $setting ) {
			// @todo Now log the Stream action here.
			/*
			 * Obtaining the name for the Stream action will be a bit tricky, and will
			 * not be bulletproof. Basically what you have to do is iterate over
			 * $wp_customize->controls() and try to find a control that is associated
			 * with this $setting. Then you can try to use $control->label. Beware,
			 * however, that a control can be associated with multiple settings.
			 */
		} );

		$actions_added[ $id_base ] = true;
	}
}, 100 );
```
