### ISSUE TITLE
Some post types and taxonomies being duplicated by connectors

### ISSUE THREAD

**Issue by fjarrett** [xwp/stream#612]
@shadyvb I noticed that in the search filters there were some post types and taxonomies being loaded by the Posts and Taxonomies connectors and are then duplicated by other connectors.

I noticed that our approach here has been to [override the record array](https://github.com/wp-stream/stream/blob/2.0.0-beta/connectors/class-wp-stream-connector-woocommerce.php#L577) and just replace the connector/context accordingly.

However, these are still being loaded into the filters because they are not officially excluded from the other connectors.

For instance the EDD taxonomy `download_tags` appears under EDD and Taxonomies in the filters. And WooCommerce `product` post type appears under Posts as well as under WooCommerce. These are just two examples, there are more and this applies to several other connectors.

Is there a way we can exclude these from Posts and Taxonomies on a later hook? I added a filter for Taxonomies in https://github.com/wp-stream/stream/commit/09ce5ad5291614fcdbe8dd28d99486a6eabbd425

![screen_shot_2014-09-07_at_5_07_41_pm](https://cloud.githubusercontent.com/assets/522158/4179883/7d835232-36db-11e4-941f-1849d6f62519.png)

![screen_shot_2014-09-07_at_5_07_50_pm](https://cloud.githubusercontent.com/assets/522158/4179884/813b006e-36db-11e4-9794-89793b98d6b0.png)

**Comment by lukecarbis** [comment]
This problem seems to have been resolved in the current version.
