### ISSUE TITLE
Allow for blocking requests on WP_Stream_DB::store() and WP_Stream_Log::log() 

### ISSUE THREAD

**Issue by sc0ttkclark** [xwp/stream#712]
`WP_Stream_DB::insert()` could get `$blocking` added and passed into `WP_Stream_API::new_records()`, which WP_Stream_DB::store() could set `$blocking` through a filter, which gets passed `$records`. The filter would get placed after the `$records` themselves are filtered and confirmed not empty. That's passing a var down the line, so maybe an alternative would be to filter $blocking directly in `WP_Stream_DB::insert()`.

Through this enhancement, code could be written that runs via cron without timeout / UI limitations, so that if the logging fails, it would be immediately available and known. Since requests are currently all non-blocking (`'blocking' => false`), it's hard to handle failures in tracking on data when the API has a problem or becomes unavailable.

For example, I could write code for a project that logs things from a temporary queue -- ran via cron every 5 or 10 minutes -- and if it fails, it won't remove the logging from the queue and instead retry on each subsequent cron run to log that temprarily queued log until it succeeds. At that point, it's removed from the queue and I know I can depend on all logging to be 100%, no data / tracking loss since there'd be a fallback queue handler.

**Comment by sc0ttkclark** [comment]
Related #711

**Comment by lukecarbis** [comment]
No longer applicable in Stream 3.0.
