### ISSUE TITLE
WP_Stream_Author not found

### ISSUE THREAD

**Issue by lukecarbis** [xwp/stream#729]
Some users are reporting this error when updating via WP CLI.

```
PHP Fatal error:  Class 'WP_Stream_Author' not found in /var/www/html/wp-content/plugins/stream/classes/class-wp-stream-log.php on line 69
```

**Comment by lukecarbis** [comment]
This is strange – `class-wp-stream-log.php` doesn't exist in Stream 3.0.

**Comment by lukecarbis** [comment]
Okay, my guess is this:

Our Github repo is located at xwp/stream.git (it used to be wp-stream/stream.git, which would cause the same problem).

If Stream was installed like so:
```
git clone https://github.com/xwp/stream.git
```

Then it would install in the `stream` directory.

However, our Wordpress.org plugin is located at wordpress.org/plugins/wp-stream. When you update, it will go into a `wp-stream` directory.

I believe that this discrepency is what is causing the error.

@japh - can  you confirm?

**Comment by fjarrett** [comment]
I just got the error while updating Stream on my personal site.

<img width="955" alt="screen shot 2015-08-25 at 9 53 24 am" src="https://cloud.githubusercontent.com/assets/522158/9469954/401a7396-4b0f-11e5-838d-ac38695bfa2d.png">

**Comment by fjarrett** [comment]
@lukecarbis Maybe it's happening during plugin update because the author class gets removed and the log class is still referencing it before it has been removed? That's one theory anyway.

**Comment by lukecarbis** [comment]
@fjarrett Makes sense. I'll look into this some more - but at this stage it's hard to image what I could possibly do to fix it. Almost seems like a sort-of-bug in `2.0.5`, which won't be around anymore in `3.0`.
