### ISSUE TITLE
Migrate Stream 1 to Stream 3?

### ISSUE THREAD

**Issue by MarioKnight** [xwp/stream#733]
I have a handful of clients whom did not make the jump to Stream 2 for one reason or another.  With the recent announcement of Stream 3 being brought back to local storage and no wordpress.com login needed, I would like to get them to Stream 3.  Testing with a site where the records aren't as important, I was hoping that the conversion process would detect the local storage of Stream 1 and perform the conversion, however it appears I was incorrect.  After the update, there was no prompt for conversion, and the current record display has much of the information missing.  The information that remains is the summary description, time stamp, and IP address.  The user, context, and action are either blank or n/a.  I updated a plugin afterwards of which no record was made.

I was wondering what the preferred method of upgrading from 1 to 3 might be, or if there is anything currently being made to streamline this process.  Thank you in advance for any assistance you can provide.

**Comment by lukecarbis** [comment]
Hi MarioKnight. Thanks for your feedback.

I _did_ test this process, but I'm sorry to say that it fell off my radar at one point. Please hold off updating your other installs, I'll try to get this right for version 3.0.1.

**Comment by lukecarbis** [comment]
Some more information from the WordPress.org repo:

> It appears the wp_stream_db option is not updating during the update routine.
>
> It also appears that the Stream DB tables are not updating/upgrading during the plugin update routine.
>
> Stream previously used, from what I can tell, three tables - stream, stream_context, and stream_meta. The Type of these tables was InnoDB, and the Collation was utf8_general_ci.
>
> Stream 3.0 uses two tables, stream and stream_meta, and now the Type is MyISAM and the Collation is utf8mb4_unicode_ci.
>
> On two websites that now have Stream 3.0 I've chosen the "Uninstall" quick option, and clicked "OK" when asked if I was sure I wanted to do this, since it would delete all Stream database tables.
>
>Then I activated Stream and records started showing on the Stream Records page, and the data in those records appeared to be complete.
>
>Simply deactivating, deleting, and reinstalling doesn't accomplish this. I also manually deleted the Stream database tables on one install, which led to some complications after reinstalling the plugin.
>
>All that to say, uninstalling the plugin and allowing the database tables to be deleted seems to allow 3.0 to work as intended.

**Comment by MarioKnight** [comment]
Hello Luke,

I'll hold off for 3.0.1 then, thanks for the updates and looking into it!
