### ISSUE TITLE
Illegal string offset 'connector' in WooCommerce connector

### ISSUE THREAD

**Issue by lukecarbis** [xwp/stream#737]
Reported by @marioknight:

We use dedicated servers running cPanel/WHM which I have root access to. The sites that show these issues have PHP 5.4.43 running. There is also a server with PHP 5.6.11 running, however the one active Stream installation on that server converted with no issues.

Between my messages in this thread, I have discovered that the site that fails to show the percentage bar has additional error messages when I update other plugins:

Warning: Illegal string offset 'connector' in /home/xxxx/public_html/wp-content/plugins/stream/connectors/class-connector-woocommerce.php on line 611

Warning: Illegal string offset 'connector' in /home/xxxx/public_html/wp-content/plugins/stream/connectors/class-connector-woocommerce.php on line 613

Warning: Illegal string offset 'connector' in /home/xxxx/public_html/wp-content/plugins/stream/connectors/class-connector-woocommerce.php on line 615

The above messages loop a number of times, though don't appear to affect the update process.

**Comment by lukecarbis** [comment]
@bordoni Would you mind having a look at this?

**Comment by bordoni** [comment]
Assign it to me :wink:

**Comment by lukecarbis** [comment]
I can't - we're still setting up teams and everything since Stream joined XWP. Can you please fork the plugin, make a new branch from `develop`, and then issue a PR against `develop`?

**Comment by bordoni** [comment]
Ahh ok, no problems. I will PR it later on.
