### ISSUE TITLE
500 Internal Server Error 

### ISSUE THREAD

**Issue by jhkoning** [xwp/stream#738]
Hi there,
I get the above error when using in conjunction with MainWP: https://mainwp.com/
This is consistent with all sites running this plugin.
I'm running the latest version of MainWP Child - 2.0.24
Cheers,
Jas

**Comment by bordoni** [comment]
Can you activate the `WP_DEBUG` and provide us which error happens?

**Comment by jhkoning** [comment]
Sure thing, standby...

**Comment by jhkoning** [comment]
Ok, interestingly enough I've just had a new error.
I set up a standalone site to debug this, it's fresh WP 4.3 - no other plugin's activated;

Parse error: syntax error, unexpected T_STRING in /var/www/vhosts/aotearoawebdesign.co.nz/subdomains/dev/httpdocs/wp-content/plugins/stream/stream.php on line 37

Stream installed via Dashboard.

**Comment by lukecarbis** [comment]
@jhkoning What version of PHP are you using?

**Comment by jhkoning** [comment]
Hi Luke,
Most will be on 5.3
Had no trouble running the previous version of Steam - have the requirements changed?
Jas
On 1 September 2015 at 8:58:12 am, Luke Carbis (notifications@github.com) wrote:

@jhkoning What version of PHP are you using?

**Comment by lukecarbis** [comment]
No, the requirements haven't changed. PHP 5.3 is required as always. The error you reported sounds like a version of PHP which doesn't support Namespaces (which was introduced in PHP 5.3).

**Comment by lukecarbis** [comment]
@jhkoning I'm going to close this ticket for now, since the MainWP issue has been addressed here:
https://github.com/mainwp/mainwp-child/pull/6

If you can confirm that the other error you're getting is happening on PHP >= 5.3, then please open a new ticket and include your PHP version, and as much other relevant information as possible.
