### ISSUE TITLE
No option to hide previous records in exclude rules

### ISSUE THREAD

**Issue by lukecarbis** [xwp/stream#740]
I'm not 100% sure that this _should_ be implemented, because of some technical limitations, but it's worth exploring properly.

I'll post my findings in this issue - let's have the discussion.

**Comment by cameronjonesweb** [comment]
I'm not too fussed whether it is implemented or not, I suppose it would be nice but if it's not possible so be it. It's just that it was mentioned in the video on the plugin page (unless I've misinterpreted it). Maybe just do a new walkthrough for v3.

**Comment by lukecarbis** [comment]
Yeah - that's going to be fixed with #730 which is milestone for 3.0.1.

**Comment by lukecarbis** [comment]
I've decided not to implement this, since we have no way of changing the visibility for an item. Plus, if we did, it would be quite difficult to do with hundreds of records (we're talking timeout issues, etc).

I don't want to delete items, because of the case where the user adds an exclude rule, then changes their mind.
