### ISSUE TITLE
Stream logo in admin sidebar missing on initial load

### ISSUE THREAD

**Issue by sirjonathan** [xwp/stream#750]
Discovered an initial where the Stream logo (as well as Jetpack) are missing on initial load. Based on our discussion over Slack it sounds like this may be related to an issue with Gravity Forms.

Here's a screenshot: https://cloudup.com/c4PETatgBlK

**Comment by lukecarbis** [comment]
@sirjonathan What version of GF?

**Comment by sirjonathan** [comment]
1.19.13

**Comment by lukecarbis** [comment]
If you turn No Conflict mode OFF (unintuitive, I know), that seems to fix the problem. I wonder if this is a bug where the setting is actually reversed...

<img width="360" alt="screen shot 2015-09-02 at 14 45 08" src="https://cloud.githubusercontent.com/assets/1097667/9623250/4cb109b2-5181-11e5-9978-0f9dd4f19e85.png">

Can you confirm?

**Comment by sirjonathan** [comment]
I can confirm. Switching "No Conflict Mode" to off resolves the issue. The logos appear properly. Switching it to "On" (and refreshing) brings the issue back.

**Comment by lukecarbis** [comment]
I'm going to put this one down as a gravity forms issue, let them know about it.
