### ISSUE TITLE
Change plugin name to Stream by XWP

### ISSUE THREAD

**Issue by lukecarbis** [xwp/stream#757]
I'd love to get some discussion happening around this idea.

One of the keys to Stream's long term success is the value it provides to [XWP](http://xwp.co). One aspect of this value is brand recognition.

One strategy used by some plugins is to use the brand name as part of the plugin name.

e.g. **Jetpack by WordPress.com**

<img width="493" alt="screen shot 2015-09-03 at 09 17 30" src="https://cloud.githubusercontent.com/assets/1097667/9647132/392d1178-521d-11e5-80bd-61c7ba562b6a.png">

Should Stream adopt this language to provide more value to XWP?

<img width="578" alt="screen shot 2015-09-03 at 09 30 29" src="https://cloud.githubusercontent.com/assets/1097667/9647267/a2c4440c-521e-11e5-8a72-7f003463f27e.png">

See also: #756 .

**Comment by Chunk69** [comment]
I personally think that is fine, just re affirms the brand behind the plugin, I say go with it.

**Comment by Japh** [comment]
Personally, I prefer it to stay as is. It does already say "By XWP" on it. Also, shorter, snappier names are better. It creates confusion about "Is it just Stream? Or is it actually Stream By XWP?"

As far as brand awareness goes, you could include a paragraph on the plugin's description page about XWP's role. Also, include XWP branding in the header image somehow.

**Comment by MaxOnTheHill** [comment]
have it as "Stream by XWP"  ... not only does it provide more value/brand recognition for XWP, but it also adds value to the product by being associated with XWP.
... any Yoast plugin is considered more highly, because it has "Yoast" in it's name.
-> Build that relationship and trust for XWP and it's offerings by using this same method ;)

**Comment by wealthyone** [comment]
trouble is we all know what Wordpress and Yoast is, but do we know what XWP is?
and the other day when you told us about Stream is, I never searched for Stream as it had nothing to do with what changed to my site were happening. Like Audit log etc etc

**Comment by kingfishercreative** [comment]
So as a brand, you have to look at if the name Stream is taken in any other type of software… An example might be Stream Accounting Software (I don’t know if that exists or not it’s just a made up one), people who use both Stream Accounting Software and WordPress might see Stream and automatically assume it’s to do with the Accounting Software when it doesn’t. Adding `By XWP` may enable people to differentiate between the two. 

As Japh stated adding some text about XWP role in the paragraph might also help brand awareness. But don't over do it, don't add so much XWP in the text that people get turned off.

**Comment by lukecarbis** [comment]
@wealthyone How do we know what Yoast is?

Searching for Stream should definitely be easier. I added some tags recently (https://github.com/xwp/stream/commit/ad0b3cbcdcae9e8f3a12f14498ec243902e67cdd), but audit log isn't one of them. I'll make an issue for that now.

**Comment by wealthyone** [comment]
@lukecarbis  Yoast in the word itself doesnt mean much I guess but it is now associated with what they do..
I guess we could say that for so many names

**Comment by Stephen-Cronin** [comment]
Shorter and simpler is better (eg Stream), but if Stream by XWP helps safeguard the future of the project, by providing XWP with branding exposure that they won't want to lose, then go with that!

I agree with @wealthyone that Yoast has much better brand awareness than XWP, but a large part of that was created through branding their plugins with Yoast in the name. So adding "by XWP" should help people recognise XWP in time.  

I will say that I like names that convey what the product does. Google Analytics by Yoast has the branding part, but also says exactly what it does. Stream doesn't do that. Stream Audit or Stream Audit Log might (but anything with Audit in it is less cool!). Not that I'm saying you should rename it to Stream Audit Log by XWP!! Too long. Just throwing some other approaches out there for you to consider.

**Comment by Japh** [comment]
> I will say that I like names that convey what the product does. Google Analytics by Yoast has the branding part, but also says exactly what it does. Stream doesn't do that. Stream Audit or Stream Audit Log might (but anything with Audit in it is less cool!). Not that I'm saying you should rename it to Stream Audit Log by XWP!! Too long. Just throwing some other approaches out there for you to consider.

"Activity Stream by XWP" ?

**Comment by MaxOnTheHill** [comment]
"A-Track by XWP"?

**Comment by wealthyone** [comment]
@Stephen-Cronin  thats what I was trying to say. About what it does.   lol

**Comment by lukecarbis** [comment]
Thanks for the thoughts @Stephen-Cronin . Much appreciated... but... I'm not going to change the name. :stuck_out_tongue:

**Comment by peterwilsoncc** [comment]
I'd be fine with "Stream by XWP", yes it marketing, yes it's building brand recognition but neither is necessary a bad thing. 

I'd like to see XWP produce a range of high quality plugins, identifying them in this fashion will help users looking for them. Brand recognition can be a two way street.

You need to remember it is a double-edged sword, mess up peoples sites and it's "broken by...". This may seem a glib sentiment but I am sincere, "by XWP" would put your name on the line each time you release an upgrade.

**Comment by westonruter** [comment]
> You need to remember it is a double-edged sword, mess up peoples sites and it's "broken by...".

:+1: 

I am reminded of WordPress.com's [alloptions size overrun error screen](https://github.com/Automattic/vip-quickstart/blob/0e54800664d4b6399ff8a0bd9e5adecbe85b6528/www/wp-content/mu-plugins/alloptions-limit.php#L36-L79):

<img width="451" alt="screen shot 2015-09-02 at 9 01 32 pm" src="https://cloud.githubusercontent.com/assets/134745/9650303/01a5fcf4-51b6-11e5-9d97-a8bdf4d32125.png">

:smile:

**Comment by cameronjonesweb** [comment]
I think it's a good idea, particularly as it is the flagship plugin for XWP. 

On the topic of the title, I think I echo other's thoughts in that the title doesn't particularly convey what it does. I'd like to see it named something along the lines of "Stream by XWP - Dashboard Activity Monitor", but that's just personal opinion.

**Comment by lukecarbis** [comment]
Thanks everyone so much for your feedback.

On weighing up everyone's thoughts, I think it's best to leave Stream as is. A few people mentioned that a simple plugin name is better, and I definitely agree with that.

More to the point though, drawing attention to XWP through the plugin name at this point won't be very effective, since Stream is XWP's only product right now.

If XWP one day has a range of plugins, and we feel that adding "by XWP" to our plugins' names will provide potential users with a mark of quality, we could revisit this.
