### ISSUE TITLE
Export functionality for reporting

### ISSUE THREAD

**Issue by kingfishercreative** [xwp/stream#759]
Allow the ability for a CSV, Excel, PDF or other type of file format for exporting for reporting. Some clients require this ability for reporting to their managers, departments etc. to justify budgets spent on websites.

**Comment by lukecarbis** [comment]
This is a great idea. I wonder whether or not this is valuable enough to a broad range of users to be in Stream core, or if it there should be a separate plugin which enables this functionality. I want to balance having a robust core feature set with keeping things lean and mean.

@kingfishercreative If it were a separate plugin, would that change things for you?

**Comment by kingfishercreative** [comment]
I could see the usefulness in having it as a separate plugin. The only issue I have is when you start doing separate plugin's, most of the time they are only available via an additional fee, not everyone wants to do this.

**Comment by lukecarbis** [comment]
@kingfishercreative So, what your saying is that export functionality would be great, it would work best in a separate plugin as a Stream extension, and it should be free - is that right?

If so, I think we could make that work.

**Comment by lukecarbis** [comment]
Closing this, since it's a great idea but doesn't belong in core Stream.

**Comment by lukecarbis** [comment]
@kingfishercreative We changed our mind. :stuck_out_tongue: It's in the 3.0.5 release. Free.

If you like Stream, and would use the Export feature - we'd be very grateful if you left us a review on WordPress.org. https://wordpress.org/support/view/plugin-reviews/stream#postform
