### ISSUE TITLE
Stream Records list table design refresh

### ISSUE THREAD

**Issue by lukecarbis** [xwp/stream#761]
In a long list like Stream's records table, visual cues can help users find what they are looking for faster. 

The user profile image is a good start, why not expand that? How can we visually enhance each context for better skim-ability?

**Comment by jordesign** [comment]
I think it could be interesting (when notifications exist) for users to set certain contexts/actions to be highlighted in the list?

**Comment by lukecarbis** [comment]
Oh! Great idea.

**Comment by jordesign** [comment]
Proposed UI change for the list table design.
![streamlist_v3](https://cloud.githubusercontent.com/assets/1842363/9674797/d21aefdc-52f8-11e5-916d-19e20084fccc.jpg)

**Comment by lukecarbis** [comment]
:heart_eyes_cat: Very nice.

I like your thinking on the date - hiding the date for recent entries with the current date, and hiding the time for older entries. I feel that the extra information should still be visible somehow. A tooltip?

Also, on the date format, I think we should stick with Y/m/d. See @fjarrett's comment here: https://github.com/xwp/stream/issues/353#issuecomment-38757040

**Comment by lukecarbis** [comment]
Suggestion for displaying users here:

"It would be good to see the user's full name in cases where the users share a screen name. For example, I have websites for clients that display their name publicly (on the blog for example) as the company name and there can be a number of users doing this on the same website, but as that is what stream uses also it become confusing who is who."

From https://wordpress.org/support/topic/feature-request-370?replies=1

**Comment by lukecarbis** [comment]
@jordesign Planning on working on this one soon. Think you could offer an updated concept, based on the two suggestions above? I'd also be keen for your thoughts on this related issue: #595 .

**Comment by jordesign** [comment]
@lukecarbis will do - try and look at this in the next few days. Re: Full Name - do you think instead of display name? or as well as?

**Comment by lukecarbis** [comment]
@jordesign Actually, my thoughts on this is that we should use the existing WordPress convention of using the "Display name". This is what the "Author" column in the posts list table uses, and Stream should do the same.

It might be helpful to include a title tag with the username, so one could hover over the name if there's a duplicate, but that doesn't need to be included in the design.

What do you think?

**Comment by jordesign** [comment]
Agreed - better to go with convention - but adding a 'title' attribute for the tooltip would be a nice touch.

**Comment by jwold** [comment]
@lukecarbis is the next step for a new UI concept of this? I may have bandwidth next week to jump in and help with a concept. Not sure about @jordesign's availability. Thanks!

**Comment by lukecarbis** [comment]
@jordesign - think we could get a refresh of your concept, based on the discussion?

**Comment by jordesign** [comment]
@jwold @lukecarbis Here's an updated visual - keen for feedback.
![streamlist_v4](https://cloud.githubusercontent.com/assets/1842363/11431697/86fe3708-94f1-11e5-832e-a37d90817751.png)

**Comment by fjarrett** [comment]
Big 👍 from me FWIW!

**Comment by jordesign** [comment]
Thanks @fjarrett - much appreciated
