### ISSUE TITLE
Stream Notifications

### ISSUE THREAD

**Issue by lukecarbis** [xwp/stream#762]
Notifications were a premium feature in version 2 of Stream, and I'd like to reintroduce them into Stream 3 for free.

At the same time, I'd like to redevelop them from the group up, and rethink the interface.

The user should be able to create rules for various situations (i.e. If an administrator publishes a post on Saturday), and choose a notification type.

At launch, the user should be able to choose from these notification types:
- Stream Records table highlight
- Email
- Zapier
- IFTTT

**Comment by shadyvb** [comment]
We can also provide desktop notifications through [service workers](https://www.chromestatus.com/feature/5480344312610816), which would be a great way to provide real-time notifications, and possibly actionable messages as well, if we currently have any.
