### ISSUE TITLE
Gravity forms error when deleting a form.

### ISSUE THREAD

**Issue by lukecarbis** [xwp/stream#771]
`( ! ) Strict standards: Only variables should be passed by reference in /srv/www/wordpress-develop/src/wp-content/plugins/stream/connectors/class-connector-gravityforms.php on line 726`

Also, trashing a form isn't tracked.

**Comment by lukecarbis** [comment]
Not completely resolved yet.

**Comment by rob** [comment]
See #780. Still issues. I just submitted some more fixes. I'll keep working on it this week and see if I can make sure the connector is 100% fixed.

**Comment by lukecarbis** [comment]
Resolved in #781.
