### ISSUE TITLE
Repeating "changes" from cronjob / IP filtering

### ISSUE THREAD

**Issue by lukecarbis** [xwp/stream#772]
Everytime my multsite cronjob runs (i.e. every 5 minutes), stream reports "blog_id" and "time" settings changed for each site. I've been trying to exclude those spurious mesasges via the filtering mechanism, but IP based filtering does not seem to work at all.

Reported here: https://wordpress.org/support/topic/repeating-changes-from-cronjob-ip-filtering

**Comment by pep-** [comment]
Should we split this into separate issues? I assume that the cron-caused messages are not directly involved with IP-based filtering.

**Comment by lukecarbis** [comment]
@mundschenk-at Which cron is running which causes this? `update_network_counts`?

**Comment by lukecarbis** [comment]
@mundschenk-at I have been able to fix the exclude issue, but I've not been able to replicate the addition extraneous reports. Can you help me to reproduce them?

**Comment by mundschenk-at** [comment]
@lukecarbis It's a custom multisite cronjob that call's wp-cron.php from a shell script.

**Comment by lukecarbis** [comment]
@mundschenk-at In that case I'll leave it to you to figure out why it's changing the `blog_id` and `time`. The exclude rules problem should now be fixed.

**Comment by mundschenk-at** [comment]
@lukecarbis It's custom in so far ihat it calls wp-cron.php for each site in the multisite network (with `define(‘DISABLE_WP_CRON’, true)`), but that's all just using standard WP functionality. I don't think the mechanism (via a real cronjob or on every page load) of calling wp-cron.php should matter much here.

**Comment by lukecarbis** [comment]
I'd say it would be related to one of the cron jobs that are running. Are any custom? You can use Debug Bar with a Debug Bar Cron add-on to see which cron jobs are scheduled. I've tried running all the default cron jobs and I can't replicate.

**Comment by mundschenk-at** [comment]
@lukecarbis Not custom as in made by me, but of course various events by several different plugins are scheduled. However, while I've been able to trigger the bug on a site with very few plugins by manually triggering an event via the plugin WP Crontrol, it's not been repeatable (and the calls don't appear totally regularely), so there seems to be some kind of race condition. Could these messages be triggered by some combination of calls to `switch_to_blog`?

**Comment by lukecarbis** [comment]
@mundschenk-at Yes, that could make sense. If you're able to replicate the issue, let me know.
