### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by 13pixlar** [xwp/stream#786]
This is a feature request regarding Stram and Gravity Forms.

We run a fairly complex multisite with lots of sites and even more forms. It would be awesome to track/log every user form interaction. Not edits to the form but sibmits/edit/deletes of entries on the front end.

We run many simultanious events that users sign up for using fairly complex forms that they can come back and edit at a later time. 

We have lots and lots of submissions being entered, updated and deleted on any given day. Tracking all this in a manageable way would be great.

**Comment by lukecarbis** [comment]
@13pixlar This should be implemented in #780 .
