### ISSUE TITLE
Fatal Error on sites with Jetpack

### ISSUE THREAD

**Issue by desrosj** [xwp/stream#792]
Seeing a fatal error on sites that have Jetpack enabled. Stream Records page loads until a Jetpack event is hit, and stops.

PHP Fatal error:  Class 'WP_Stream\Jetpack' not found in site/path/on/server/wp-content/plugins/stream/connectors/class-connector-jetpack.php on line 171.

**Comment by sirjonathan** [comment]
Noticing the same error here.
