### ISSUE TITLE
Records page doesn't fully load / datepicker js error

### ISSUE THREAD

**Issue by rob** [xwp/stream#795]
This only happens on one of our sites (we have a bunch.)

Trying to load the main records page causes a fatal js error:

`admin.js?ver=3.0.3:20 Uncaught TypeError: datepickers.datepicker is not a function`

![stream-page](https://cloud.githubusercontent.com/assets/503/11150792/c0d46222-89f7-11e5-8c5d-cd1387bc1a31.png)

Trying to go to other record pages (such as `/admin.php?page=wp_stream&paged=3`) brings mixed results - some pages are blank, some show a couple of records and then the page doesn't finish rendering. Any idea? I can look at it later when I have some time.

**Comment by lukecarbis** [comment]
Hi @rob. Re: the fatal js error - could this be a plugin conflict? What other plugins are you running on the site? Can you turn them all off, see if it still happens?

Regarding the blank pages... I've a feeling it's related to #792.

**Comment by rob** [comment]
Hi @lukecarbis - you're right, it looks like Jetpack is the cause of this issue. I disabled Jetpack and everything works as it should. I'll close this as it's a duplicate of #792.
