### ISSUE TITLE
Cloudflare IP Address

### ISSUE THREAD

**Issue by lukecarbis** [xwp/stream#803]
IP Addresses are incorrect when the site is behind Cloudflare. See http://stackoverflow.com/questions/14985518/cloudflare-and-logging-visitor-ip-addresses-via-in-php.

**Comment by lukecarbis** [comment]
Issue is resolved by installing the Cloudflare plugin: https://wordpress.org/support/topic/inconsistent-display-of-events-and-ip-address-belongs-to-server?replies=5#post-7716456

**Comment by imeson** [comment]
I am having the same issue but with Fastly https://www.fastly.com/
We are using the plugin they recommend https://wordpress.org/plugins/purgely/
Should I follow up with them about the ability to restore the correct IP? Doesn't seem like it should be an issue on here but wanted to doublecheck. 

Thanks!
