### ISSUE TITLE
CSV Export

### ISSUE THREAD

**Issue by glenp** [xwp/stream#813]
Feature request - would be great to export Stream data to a CSV file for analysis. For example, I want to know the top 10 most active user accounts by login to measure engagement. Currently I can only see the activity on a user-by-user basis so it would be great to quickly slice and dice the data in a more portable form.

**Comment by osprime** [comment]
I agree with an CSV export but my case is to send clients an update of actions that were preformed on their sites. Currently copy and pasting the progress tends not to look good in email.

**Comment by lukecarbis** [comment]
Great idea. I think CSV is going to be the most light-weight and flexible solution, short of a fully fledged Stream Reports plugin. I think an "Export CSV" link at the bottom left of the Stream list would work well.

The exported CSV should respect the current filtering rules, too.

@chacha Any other ideas? Would you be happy to implement this?

**Comment by chacha** [comment]
@lukecarbis Sounds like a great idea! I find CSV exports incredibly useful for when I just need to get something into a Google Sheet. I'll get this going right away.

**Comment by lukecarbis** [comment]
@glenp @osprime Thanks so much for your suggestion. We built it! CSV and JSON export are included in the 3.0.5 update, especially for you.

@chacha and I would be very grateful if you left us a review on WordPress.org. https://wordpress.org/support/view/plugin-reviews/stream#postform
