### ISSUE TITLE
Make custom connector documentation more beginner-friendly

### ISSUE THREAD

**Issue by sirjonathan** [xwp/stream#819]
https://github.com/xwp/stream/wiki/Creating-a-Custom-Connector

Offer more complete start-to-finish guidance. A few specific suggestions:
- give them a complete plugin file that they can edit and drop in place (i.e. include plugin headings). 
- explain, outside of code documentation, how triggering Stream works (i.e. the callback to the action)
- Offer some actual examples along with the foo / bar (i.e. wanting to trigger Stream when some action happens in a custom plugin)

**Comment by kopepasah** [comment]
@kasparsd I feel this could better be served by an example plugin repo or template repo for creating connectors. Thoughts?

**Comment by delawski** [comment]
Related: #1500

**Comment by delawski** [comment]
I'm closing this one via #1500.
