### ISSUE TITLE
Multisite: No way to exclude Super Admins?

### ISSUE THREAD

**Issue by clubdesign** [xwp/stream#829]
Hey Guys,

thanks for your great work, but we have a problem here, i can't exclude Super Admins from Tracking. We have 3 Super Admins on our site (60 Subsites) and i can't find them within the select on the exclude screen (The role is missing and these 3 Users are missing). All of the Super Admins Activity is tracked right now. I don`t know how you get the users right now, but Super Admins don't have to attached to a blog, so maybe the Users Query needs to be adjusted?

Is there any filter available to manually exclude those users? Can't find anything in the docs (and was too lazy yet to read through the code ;) ).

Greets Marcus

**Comment by clubdesign** [comment]
Forget my Laziness, just went into code, as far as i can see, the only option currently is to hook into your `wp_stream_settings_options` filter and add the user_ids i need to exclude rules. That seems to work smoothly, but it should be made easier for this case ;)

```
add_filter("wp_stream_settings_options", function( $wp_stream_rules ) {

  $exclude_user_ids = array(1);

  if( array_key_exists("author_or_role", $wp_stream_rules["exclude_rules"] ) || !is_array( $wp_stream_rules["exclude_rules"]["author_or_role"] ) ) {
    $wp_stream_rules["exclude_rules"]["author_or_role"] = $exclude_user_ids;
  } else {
    $wp_stream_rules["exclude_rules"]["author_or_role"] = array_merge( $wp_stream_rules["exclude_rules"]["author_or_role"], $exclude_user_ids );
  }

  return $wp_stream_rules;

 }, 10, 1 );
```
By the way, thumbs up for your clean code, i wish other plugins work like that!

**Comment by lukecarbis** [comment]
@marcin-lawrowski Could you look into this? It shouldn't be hard to do the following:

1. Check if the Stream is running on multisite
2. Check if the current user is a super admin, and if so
3. Include super admins in the dropdown list of users

Let's make sure this works on the Exclude screen as well as the User filter screen.
