### ISSUE TITLE
Keep Records For setting not working

### ISSUE THREAD

**Issue by lukecarbis** [xwp/stream#830]
It looks like the cron which is supposed to run to check if there's any old records to delete isn't working.

Reported here: https://wordpress.org/support/topic/close-to-180-days-of-records-even-after-selecting-30-days-in-settings?replies=2

**Comment by chacha** [comment]
Verified base functionality is working outside of cron job. Something about the cron job, however, is making it not fire. Tried manually firing off the cron job via a plugin (WP Control) and the records are not being cleared.

**Comment by chacha** [comment]
Looks like the query is running, but it is never matching records.

**Comment by chacha** [comment]
So, it looks like the admin class is never loaded during a cron job, which means that while the cron event is scheduled, the actual functionality is never hooked up to execute.

The easiest fix for this would be to load the admin class during cron.

**Comment by lukecarbis** [comment]
👌
