### ISSUE TITLE
Errors on WPMU DEV dashboard

### ISSUE THREAD

**Issue by cameronjonesweb** [xwp/stream#839]
Getting the following errors on the WPMU DEV dashboard when first logging in. Any subsequent views do not generate the error.

```
Warning: array_keys() expects parameter 1 to be array, string given in C:\xampp\htdocs\portfolio_2015\wordpress\wp-content\plugins\stream\connectors\class-connector-settings.php on line 336

Warning: array_filter() expects parameter 1 to be array, null given in C:\xampp\htdocs\portfolio_2015\wordpress\wp-content\plugins\stream\connectors\class-connector-settings.php on line 336
```

**Comment by chacha** [comment]
@cameronjonesweb Could you let us know version information?

**Comment by cameronjonesweb** [comment]
Stream: 3.0.5
WPMU Dashboard: 4.0.8
Running WordPress 4.4.2 on a localhost

**Comment by lukecarbis** [comment]
Line at fault: https://github.com/xwp/stream/blob/develop/connectors/class-connector-settings.php#L363

**Comment by chacha** [comment]
Wanted to verify if it was occurring in a normal single install site, which I was not able to reproduce. Going to try it out on a MS next.

**Comment by lukecarbis** [comment]
@cameronjonesweb I can't replicate in WPMU Subdomain Dev - but I can take a guess at what's causing it. Could you please checkout the `bugfix/issue-839` branch, and see if that resolves the issue?

**Comment by cameronjonesweb** [comment]
Looks like that has fixed the issue.
