### ISSUE TITLE
Custom post type - Users not seen

### ISSUE THREAD

**Issue by robertandrews** [xwp/stream#846]
I have a custom post type, called Press Mentions (pressmentions).
Stream is properly recognising the posts, but it is not displaying the users who authored them.
Instead, I'm seeing a "WP" logo and "N/A".
See screengrab here: http://i.imgur.com/a6cnAhC.png

The Custom Posts that are being added are being authored by users who also have a custom role... "Analyst".

How can I fix this?
I note that Stream should work with Custom Post Types.
What should I be looking for?

**Comment by robertandrews** [comment]
I've tested that my Stream is successfully logging a standard post type action for a custom-role user, and it is.
So the problem seems to be only with the custom post type.
I am now wondering if the problem is because the custom post types are controlled by the Pods plugin.

**Comment by lukecarbis** [comment]
Hi Robert,

This problem has cropped up before but we've been unable to reproduce it. Maybe the Pods plugin is the cause!

Could you please provide full steps to reproduce, including instructions on installing and setting up Pods, and creating the CPT?

**Comment by robertandrews** [comment]
I can confirm it's not Pods at fault.
I have now removed Pods and am using custom post types via manual code in functions.php.
I can post more info...

**Comment by robertandrews** [comment]
@lukecarbis 

Let me show you the code I use to set up the custom post type, in functions.php...

`// Set up Press Mentions post type https://generatewp.com/snippet/ddyykkn/
// Register Custom Post Type
function pressmentions_post_type() {

	$labels = array(
		'name'                  => 'Press Mentions',
		'singular_name'         => 'Press Mention',
		'menu_name'             => 'Press Mentions',
		'name_admin_bar'        => 'Press Mention',
		'archives'              => 'Item Archives',
		'parent_item_colon'     => 'Parent Item:',
		'all_items'             => 'All Items',
		'add_new_item'          => 'Add New Item',
		'add_new'               => 'Add New',
		'new_item'              => 'New Item',
		'edit_item'             => 'Edit Item',
		'update_item'           => 'Update Item',
		'view_item'             => 'View Item',
		'search_items'          => 'Search Item',
		'not_found'             => 'Not found',
		'not_found_in_trash'    => 'Not found in Trash',
		'featured_image'        => 'Featured Image',
		'set_featured_image'    => 'Set featured image',
		'remove_featured_image' => 'Remove featured image',
		'use_featured_image'    => 'Use as featured image',
		'insert_into_item'      => 'Insert into item',
		'uploaded_to_this_item' => 'Uploaded to this item',
		'items_list'            => 'Items list',
		'items_list_navigation' => 'Items list navigation',
		'filter_items_list'     => 'Filter items list',
	);
	$args = array(
		'label'                 => 'Press Mention',
		'description'           => 'Press mentions.',
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'excerpt', 'author', 'thumbnail' ),
		'taxonomies'            => array( 'category', 'post_tag' ),
		'hierarchical'          => true,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'menu_icon'             => 'dashicons-megaphone',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'post',
		'register_meta_box_cb'	=> 'add_pressmentions_metaboxes',
	);
	register_post_type( 'pressmention', $args );

}
add_action( 'init', 'pressmentions_post_type', 0 );`

The actual post creation is done by a custom plugin I have had written.
The detail is of that is: for each of my users, then, for each item in a corresponding RSS feed, insert the RSS item contents as the post content of a "pressmention" custom post, both standard and custom meta data.
The relevant code from the plugin is below...

`		foreach($feeds as $feed) {
			$page = get_page_by_title($feed['title'], ARRAY_A, 'pressmention');
			
			if(is_null($page)) {
			
				$feed['date'] = gmdate('c', strtotime($feed['date']));
				
				$postdata = array(
					"post_author" => $userId, 
					"post_type" => "pressmention",
					"post_date" => $feed['date'],
					"post_date_gmt" => $feed['date'],
					"post_title" => $feed['title'],
					"post_status" => "publish",
					"post_content" => $feed['story'],
				);
				
				$id = wp_insert_post($postdata, true);
				
				add_post_meta($id, "press_mention_information_story-link", $feed['link']);
				
				if($feed['image'] != "") {
					add_post_meta($id, "press_mention_information_image", $feed['image']);
				}

				if($feed['publication_name'] != "") {
					add_post_meta($id, "press_mention_information_publication-name", $feed['publication_name']);
				}

				if($feed['publication_url'] != "") {
					add_post_meta($id, "press_mention_information_publication-url", $feed['publication_url']);
				}
			}
		}`

This will be set to run by cron but, for now, the plugin has only been initiated by SSH.
So, if you like, the posts are being created by a plugin - but they are being created against actual (custom) users' profiles.

Hope you can help.
Thanks.

**Comment by robertandrews** [comment]
Any ideas on this?

**Comment by lukecarbis** [comment]
@robertandrews Next step is to try to replicate the issue, so we can find out what's causing it.

@chacha Can you please see if you can get it to happen for you?

**Comment by robertandrews** [comment]
Curious about whether you found anything. Still experiencing the issue at my end.

**Comment by chacha** [comment]
Apparently this got out of my inbox somehow. I will take a look today.
Sorry about that.

**Comment by chacha** [comment]
@robertandrews Stream logs the user id based on a [call](https://github.com/xwp/stream/blob/develop/classes/class-log.php#L49) to `get_current_user_id()` which is based off the current logged in user. 

Unless your cronjob sets the user variables in WordPress such that it appears that the user is logged in, it will log it to the cronjob. We don't base the log off of the `post_author` line as that is always set to the original author and not necessarily the person performing the action (updates, for instance)

Without delving too deep into your code, do you think this might be the cause of the problem you're seeing?

**Comment by chacha** [comment]
And if this is true, the easiest way to fix the recording specifically for your plugin would be to create a handler that modifies the user using the `wp_stream_record_array` [filter](https://github.com/xwp/stream/blob/develop/classes/class-db.php#L92).

**Comment by robertandrews** [comment]
@chacha Thanks.
I'm not developer enough to know the answer. The plugin was commissioned externally.
I could show you some code if you like.
