### ISSUE TITLE
Front-end display of Stream data planned?

### ISSUE THREAD

**Issue by twiginteractive** [xwp/stream#848]
Is there any plans to include a shortcode that would display Stream data on the front-end? It could include filtering params etc. as a shortcut to the ->db->query() function.

I need to do this, so I'm planning to have to make my own shortcode that pulls the Stream data, spits it out as JSON and then consume & display it with DataTables. Curious if this is something in the development roadmap?

**Comment by lukecarbis** [comment]
It's not. Stream's focus is in the admin.
