### ISSUE TITLE
.mailmap file included in zip on wordpress.org

### ISSUE THREAD

**Issue by jamesgol** [xwp/stream#850]
Noticed the .mailmap file in the zip download from wordpress.org.  Not sure what your process is for exporting to svn, but should probably get included in the exclusion list.

**Comment by chacha** [comment]
This could be added to the exception list. I've added the issue to our `wp-dev-lib` development kit [here](https://github.com/xwp/wp-dev-lib/issues/180).

**Comment by jamesgol** [comment]
Didn't realize the wp-dev-lib library took care of this, so I added a PR for it.
