### ISSUE TITLE
Users ajax load never called

### ISSUE THREAD

**Issue by evgenykireev** [xwp/stream#853]
I see you have code to load users list filter using ajax. $ajax parameter is responsible for it in
https://github.com/xwp/stream/blob/84e02d3e43679188aea677516d147c62c81e3401/classes/class-list-table.php#L661
However, that method is only called from
https://github.com/xwp/stream/blob/84e02d3e43679188aea677516d147c62c81e3401/classes/class-list-table.php#L624 and $ajax parameter is never passed. 

I created a PR to fix it https://github.com/xwp/stream/pull/854

**Comment by lukecarbis** [comment]
Resolved in #854.
