### ISSUE TITLE
Installation through wp-cli don't create database tables

### ISSUE THREAD

**Issue by wrongware** [xwp/stream#858]
If I tried for example:
```
wp plugin install stream --activate
wp plugin deactivate stream
```
then I got error:
> Chyba databáze WordPressu: **Table 'wpscaffolding.prefix_stream' doesn't exist**. Konkrétní dotaz: SHOW FULL COLUMNS FROM `prefix_stream`. Příslušná funkce: include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/php/wp-cli.php'), WP_CLI\Runner->start, WP_CLI\Runner->_run_command, WP_CLI\Runner->run_command, WP_CLI\Dispatcher\Subcommand->invoke, call_user_func, WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}, call_user_func, Plugin_Command->deactivate, deactivate_plugins, do_action('deactivate_plugin'), call_user_func_array, WP_Stream\Connector->callback, call_user_func_array, WP_Stream\Connector_Installer->callback_deactivate_plugin, WP_Stream\Connector->log, call_user_func_array, WP_Stream\Log->log, WP_Stream\DB->insert.
> Success: Plugin 'stream' deactivated.
```

If i ran wp server and then I open WordPress administration, the tables were created.

**Comment by chacha** [comment]
It appears that the tables are only created when we run the `Install::check()` method which only happens when an `init` hook is ran. This likely means that the tables wouldn't be installed until a command gets ran on WP-CLI that triggers the `init` hook.

After a quick review of WP-CLI, it doesn't look like the `init` hook is ran on activation, which is likely the cause of the problem. Currently looking for a way to do a manual firing of `init`, but that isn't proving to be simple.

**Comment by wrongware** [comment]
Maybe it might help https://github.com/wp-cli/wp-cli/issues/1997

**Comment by wrongware** [comment]
Hi,

I was a little digging and I [have found command](https://github.com/wp-cli/wp-cli/blob/master/php/commands/plugin.php#L272) for plugin activation 
and [there](https://core.trac.wordpress.org/browser/tags/4.5.3/src/wp-admin/includes/plugin.php#L585) is an action that should trigger [your installation procedure](https://github.com/xwp/stream/blob/develop/classes/class-install.php#L68).

(Sry for EN, i am not native)

**Comment by lukecarbis** [comment]
Hi wrongware - I'm not sure I see the action which you're referring to. Could you please send a pull request as an example?

**Comment by wrongware** [comment]
Hi Luke,

So I figured it out. [This condition](https://github.com/xwp/stream/blob/develop/classes/class-plugin.php#L101) will never happen when it is triggered via wp-cli.

I've sent pull-request [here](https://github.com/xwp/stream/pull/880).

**Comment by thefrosty** [comment]
Glad this is solved, but how about Bedrock autoload activation via mu-plugin installs?
