### ISSUE TITLE
Conflict with ACF select2 v3 bundled library

### ISSUE THREAD

**Issue by versusbassz** [xwp/stream#860]
After version 3.0.6 of "stream", it's filters are broken on my sites.
Can it be conflict with ACF select2 v3 bundled library?

![wpstream-acf-conflict](https://cloud.githubusercontent.com/assets/2342074/16837073/ca3dd702-49c9-11e6-9026-e934dcde0e2e.png)

**Comment by versusbassz** [comment]
Topic from ACF support forum: https://support.advancedcustomfields.com/forums/topic/select2-v4/

**Comment by lukecarbis** [comment]
Hi @versusbassz. Just tried to replicate this with ACF 4.4.7 and Stream 3.0.7, and it all looks good to me. You mentioned Stream 3.0.6 in your description - have you tried with 3.0.7?

**Comment by lukecarbis** [comment]
https://cloudup.com/cBp7y-0ptwY
