### ISSUE TITLE
Updating plugin just fataled my site

### ISSUE THREAD

**Issue by pdewouters** [xwp/stream#866]
`Fatal error: Class 'WP_Site' not found in /usr/share/nginx/wordpress/wp-content/plugins/stream/includes/functions.php on line 100`

I was on a version previous to 4.5.3, not sure exactly which one, because it's a site I rarely visit. I updated Stream, also not sure which version, to the latest and it caused the WSOD.

You probably need a `class_exists` check or similar

**Comment by lukecarbis** [comment]
Hi @pdewouters - thanks for making us aware of this. It looks like Stream requires the latest version of WordPress - we unknowingly introduced a dependency in the last release.

Try updating your WordPress first, then try again.
