### ISSUE TITLE
Feature Request: Aggregate Logs of Several Installations

### ISSUE THREAD

**Issue by COLABORATI** [xwp/stream#868]
Please make it possible to collect logs of multiple installations in one place, also it would be great if you supported the standard log aggregator tools like Logstash, greylog or Fluentd. or, hey, just syslog :)

**Comment by COLABORATI** [comment]
btw I just found this, you could copy some code: 
https://wordpress.org/plugins/wp2syslog/

**Comment by lukecarbis** [comment]
Great thoughts. I think this plugin aught to do the trick: https://wordpress.org/plugins/stream-to-papertrail/
