### ISSUE TITLE
Filter by User Role

### ISSUE THREAD

**Issue by lukecarbis** [xwp/stream#871]
Currently Stream only allows filtering records by User, not User Role.

The Exclude Rules have a dropdown which includes User Role. This should be used for filtering, too.

<img width="167" alt="screen shot 2016-08-25 at 07 23 31" src="https://cloud.githubusercontent.com/assets/1097667/17948605/dc0f7a9e-6a94-11e6-99c5-6f67bc9afae1.png">

**Comment by slaFFik** [comment]
Yes, please! :)

**Comment by nebbens** [comment]
Will this be added soon?

**Comment by jmslbam** [comment]
For anybody that does need this. Stream supports filtering by User Role, but doesn't have the dropdown yet.
Here's my code:


```
<?php

namespace Peinemann\Stream\Filter;

class UserRole {
	public function register_hooks() {
		add_filter('wp_stream_list_table_filters',[ $this, 'add_user_role_filter' ] );
	}

	public function add_user_role_filter( $filters ){

		$roles = get_editable_roles();
		$items = [];

		foreach( $roles as $key => $role ){
			$items[ $key ] = [ 
				'label' => $role['name'],
				'disabled' => '',
			];
		}

		if( !empty( $items  ) ) {
			$filters['user_role'] = array(
				'title' => __( 'User role', 'peinemann' ),
				'items' => $items,
			);
		}

		return $filters;
	}
}
```
