### ISSUE TITLE
wp_get_sites() deprecated notice

### ISSUE THREAD

**Issue by jacobschweitzer** [xwp/stream#874]
Reported from @paulgibbs: on the  [WordPress.org forums](https://wordpress.org/support/topic/wp_get_sites-deprecated-notice/)

>  Stream 3.0.5 on WP 4.6, the wp_get_sites is deprecated notice will appear in logs.
> I’ve had to hack this locally for now, it’s annoying in a dev env.
> Backtrace leads to WP_Stream\Connector_Blogs->get_context_labels().

**Comment by paulgibbs** [comment]
In addition to that one I reported, I'm also seeing another on multisite in wp-admin/network, on the "Stream Records" page. It appears just above the filter options above the data table:

`Notice: wp_get_sites is deprecated since version 4.6.0! Use get_sites() instead. in /srv/bindings/b319d0a7856145ceb6c74cb97401514f/code/wp-includes/functions.php on line 3707`

**Comment by jacobschweitzer** [comment]
@paulgibbs  I'm not able to reproduce this unless I comment out a portion of the code that first checks if the `get_sites()` function exists and uses it if available. So if you are on WP 4.6 the error shouldn't occur, in older versions it shouldn't either as it would use `wp_get_sites()`. Here is the offending code: https://github.com/xwp/stream/blob/develop/includes/functions.php#L89-L105

**Comment by jacobschweitzer** [comment]
So @paulgibbs I looked a bit further into this and the function which uses `get_sites` was added in Stream 3.0.6, the current version is 3.0.7 so if you are able to update that'll take care of the error.

**Comment by paulgibbs** [comment]
i'll give that a go, thanks

**Comment by grappler** [comment]
I am using Stream `3.1.1` and I am getting the notice on /wp-admin/network/update-core.php. The notice originates from `WP_Stream\Alerts->change_menu_link_url()`

**Comment by pranksinatra** [comment]
Yep, just wanted to confirm the _wp_get_sites is deprecated_ notice @grappler is seeing in /wp-admin/network/plugins.php  due to `WP_Stream\Alerts->change_menu_link_url()` in Stream 3.1.1

**Comment by lukecarbis** [comment]
Just added a fix for 3.2.2.

**Comment by grappler** [comment]
@lukecarbis Wenn is a released planned?
