### ISSUE TITLE
Class ‘WPSEO_Options’ not found

### ISSUE THREAD

**Issue by jacobschweitzer** [xwp/stream#875]
Two WordPress.org forum posts mentioned this:
[Fatal PHP Error](https://wordpress.org/support/topic/fatal-php-error-8/)
[Update WP page not working when Stream plugin is enable](https://wordpress.org/support/topic/update-wp-page-not-working-when-stream-plugin-is-enable/)

Location of the issue:
connectors/class-connector-wordpress-seo.php on line 181

Both appear to be using WP multisite.

**Comment by lkraav** [comment]
I can confirm, it's real, and yes, happens on multi-site, but not on single-site.

**Comment by jacobschweitzer** [comment]
@lkraav Thank you for confirming that, I'll look into this today.

**Comment by paulgibbs** [comment]
I am also seeing this on a client site. I don't have first-hand knowledge of where exactly you have to go to trigger it -- i'll find out -- but the site's also using the Yoast SEO plugin, on multisite. We noticed when we updated the sites to WP 4.6 (it was running 4.5.x previously), and all themes/plugins at the same time, which included both Stream and Yoast SEO.

**Comment by jacobschweitzer** [comment]
So I was able to reproduce an error when Stream is network enabled but Yoast SEO is not network enabled. I've issued a pull request for a fix which works but has to be checked for any un-intended effects. https://github.com/xwp/stream/pull/879

**Comment by paulgibbs** [comment]
I see that PR got merged -- any estimate for when we'll get an updated release on Stream that includes it?

**Comment by lukecarbis** [comment]
We're working hard on finalising Stream Alerts. There are just a few little bugs to iron out there. We would like to release this at the same time.
