### ISSUE TITLE
Keep records option missing in Multisite

### ISSUE THREAD

**Issue by jacobschweitzer** [xwp/stream#876]
From the WordPress.org forums: [Keep records option missing in Multisite](https://wordpress.org/support/topic/keep-records-option-missing-in-multisite/)

> Hi
> I know there was a bug that removed the “keep records for xxx days” option which was resolved Version 3.0.7. But it’s still missing in multisite, unless its in a totally different place in multisite?

**Comment by mundschenk-at** [comment]
This is still the case with the latest version (3.1).

**Comment by mundschenk-at** [comment]
Works with #892
