### ISSUE TITLE
Performance issue: 70+ Stream queries per page load when not logged in

### ISSUE THREAD

**Issue by pranksinatra** [xwp/stream#878]
I was profiling [goshen.edu](https://www.goshen.edu)'s server-side performance today using the [Query Monitor plugin](https://wordpress.org/plugins/query-monitor/) and noticed that Stream consistently makes SELECT queries, regardless of whether or not I'm logged in:

![image](https://cloud.githubusercontent.com/assets/9473554/18487322/9c3bb508-79a9-11e6-83f5-e84d1e3632a3.png)

This is puzzling, as my understanding was that Stream only tracked the interactions of logged-in users. Sorry if I'm missing something obvious, but I thought I should pass this on.

**Comment by lukecarbis** [comment]
@pranksinatra - can you help me to narrow this down? What queries is it running?

**Comment by pranksinatra** [comment]
Nearly all of the queries are made by the [loop of `get_blog_details()` calls](https://github.com/xwp/stream/blob/develop/connectors/class-connector-blogs.php#L69) in `get_context_labels()` in `class-connector-blogs.php`. 

Evidently, this loops through all the blogs on the multisite on the frontend regardless of whether Stream is activated on a single blog or the network. 

Thanks again for looking into this!

**Comment by lukecarbis** [comment]
@pranksinatra Made an update to the PR. Could you please try again?

**Comment by pranksinatra** [comment]
Yep, that did it! I'm down to a single Stream query on the frontend from ~80, regardless of whether or not I'm logged in.
