### ISSUE TITLE
On Stream page - browser console error

### ISSUE THREAD

**Issue by slaFFik** [xwp/stream#884]
On this page: `/wp-admin/admin.php?page=wp_stream` I'm getting browser console error:

```
Uncaught Error: No select2/compat/inputData                              select2.js?ver=3.5.2:215
```

That error breaks js on this page (Screen options, nav menu hovers etc).

**Comment by lukecarbis** [comment]
@slaFFik What other plugins do you have installed?

**Comment by slaFFik** [comment]
```Akismet
bbPress
BP Activity Share
BP Force Profile Photo
BP Profiles Statistics
BuddyPress
BuddyPress Groups Extras
BuddyPress Last Active Users (wp-admin)
BuddyPress Search
Buddypress xProfile Rich Text Field
Cyr-To-Lat
de:comments
Easy HTTPS (SSL) Redirection
ET Shortcodes
EWWW Image Optimizer
Google Analyticator
Hueman Addons
Jetpack от WordPress.com
MailChimp User Sync
MailChimp для WordPress
ManageWP - Worker
Media Filter
PHP Compatibility Checker
Plugin Security Scanner
Plugin Vulnerabilities
Polldaddy Polls & Ratings
Post List Featured Image
SG CachePress
Show Parent Comment
Stream
Users Registered List
WP Crontrol
WP Dashboard Notes
WP Envato Affiliate Card
WP Idea Stream
WP Plugin Info Card by b*web
WP-PageNavi
WP-SpamShield
WP-Sweep
Yoast SEO
Regenerate Thumbnails```

**Comment by lukecarbis** [comment]
Hi Slava - next step would be to try disabling all the plugins and see if you still get the same error. See if you can narrow it down to a particular plugin conflict.

**Comment by slaFFik** [comment]
I know all that steps, but the site will crash because of lots of
connections (and it's live), so I won't be able to do that.

**Comment by slaFFik** [comment]
Became even worse with the latest update
![image](https://cloud.githubusercontent.com/assets/282234/19849901/5dcc7eb2-9f5e-11e6-86dc-18a01701ad1c.png)

**Comment by lukecarbis** [comment]
@slaFFik Could you please test #891?
