### ISSUE TITLE
Hide Stream from a specific list of users

### ISSUE THREAD

**Issue by logichub** [xwp/stream#885]
Cross posting from [WordPress Support forum](https://wordpress.org/support/topic/hide-stream-from-a-specific-list-of-users/) as I didn't get any response.

I tried to follow your guide available [here](https://github.com/xwp/stream/wiki/Customizing-who-can-view-and-manage-Stream#managing-stream), with a little modification. I would like to use current user ID instead of current user login, but it is not working for me.

I put following code in a custom plugin:

```
function my_site_hide_stream_from_users() {
    $user_ids = array( 2 );
    $current_uid = get_current_user_id();

    if ( isset( $current_uid ) && in_array( $current_uid, $user_ids ) ) { return true; }
    return false;
}
add_filter( 'wp_stream_disable_admin_access', 'my_site_hide_stream_from_users' );
```

What am I missing here?

**Comment by lukecarbis** [comment]
Hi @logichub sorry we missed your post on .org.

The wiki is out of date. There's an issue to update it! Here's the best way to do this right now:

```php
function my_site_hide_stream_from_users() {
    $user_ids = array( 2 );
    $current_uid = get_current_user_id();

    if ( isset( $current_uid ) && in_array( $current_uid, $user_ids ) ) {
        $stream = wp_stream_get_instance();
        $stream->admin->disable_access = true;
        remove_action( 'admin_menu', array( $stream->admin, 'register_menu' );
    }
}
add_action( 'plugins_loaded', 'my_site_hide_stream_from_users' );
```

Better yet, add the specific users to a role, and don't give the role the `view_stream` capability.

**Comment by logichub** [comment]
Hi @lukecarbis ,

Thanks for the update. I have used the above code, but it still not working. Also this line is missing the closing bracket.
`remove_action( 'admin_menu', array( $stream->admin, 'register_menu' ) );`

**Comment by lukecarbis** [comment]
Hi @logichub - I just tested out the code above, and it definitely worked for me. Make sure that you are logged in as the user with ID `2` (or change the code to match your user ID).

**Comment by cfxd** [comment]
For anyone else interested in doing this... the `plugins_loaded` hook actually fires before themes are loaded, so if you're placing this code inside `functions.php` then it will not fire. I recommend instead that you use the `after_setup_theme` hook.
