### ISSUE TITLE
Please add composer.json and this plugin into packagist.org

### ISSUE THREAD

**Issue by onnimonni** [xwp/stream#894]
Hey!

This plugin is really cool! Would it be possible to add `composer.json` into the project and also to add it into `packagist.org`?

I know this can be done with wpackagist.org but I would prefer it through packagist.org instead :).

Thanks in advance 👍

**Comment by lukecarbis** [comment]
@onnimonni What's your reason for not wanting to just use wpackagist?

**Comment by onnimonni** [comment]
Couple of reasons:
* Many projects update wpackagist much later than Github * if you decide to include some 3rd party libraries later on with composer then those packages will not be handled by composer but you would need to bundle them into the wpackagist version.
* wpackagist is one more dependancy which can just dissappear. (this is only minor reason)

Including this to wpackagist would make this more future proof in my opinion.

**Comment by kopepasah** [comment]
Stream now includes a `composer.json` and is published to packagist.org; however, there is an issue with how Packagist handles the download of the file, which does not include the built dependencies. Unless we can come up with a solution in #1073, likely the best method of installing using Composer is to add information that Composer understands to install Stream via a zip:

```json
{
  "packages": {
    "xwp/stream": {
      "3.4.3": {
        "dist": {
          "url": "https://github.com/xwp/stream/releases/download/3.4.3/stream-3.4.3.zip",
          "type": "zip"
        }
      }
    }
  }
}
```
