### ISSUE TITLE
Bulk post creation overload!

### ISSUE THREAD

**Issue by alicam** [xwp/stream#895]
Hi guys.

I've hooked Slack into wp_stream so that I can see team member updates on my WP site.

However, I have a custom-post-type with lots of ACF fields, which I bulk add/delete via a script. The effect of that bulk deletion/addition is that wp_stream records hundreds of notifications via Slack and the channel "bot" gets upset.

Not your problem. It's my problem. So my ideal fix would be to trigger a wp_stream "pause" at the start of the bulk load, and then recommence with wp_stream at the conclusion.

Is there a function call for that?

Under other circumstances I do want wp_stream to record deletions, etc... just not for this!

A

**Comment by davelozier** [comment]
Add an exclusion rule for IP 127.0.0.1 and have your script set $_SERVER['REMOTE_ADDR'] = '127.0.0.1';

That *should* work I think if the script is running locally.

**Comment by alicam** [comment]
I ended up wrapping my plugin that does the Stream->Slack thing in a conditional that checks a WP option. At the beginning of my big import I set the option to bypass the plugin, then un-set it at the end of the import. Crude but entirely adequate :)

A

**Comment by kopepasah** [comment]
Thanks for the additional detail and follow up, @alicam. I am going to close this issue as it seems to have been resolved by your work around. Please feel free to open another issue if the bulk-creation problem persists.
