### ISSUE TITLE
Time ago option and language

### ISSUE THREAD

**Issue by emmtre** [xwp/stream#903]
Is it possible to have an option to disable the time ago in the date column? The reason is that the time ago is overlapping the text in the summary column on smaller browser windows. You also need to check the new user admin language in WordPress 4.7 since the time ago is in the website language and not the user admin language.

**Comment by kopepasah** [comment]
Thanks for the feedback @emmtre. WordPress screen options would be the way to control the columns in the list table.

![screen-options](https://user-images.githubusercontent.com/911283/86818082-87b3a900-c04b-11ea-8cd0-c41489a66baf.gif)
