### ISSUE TITLE
Media connector assumes parent post exists

### ISSUE THREAD

**Issue by rmccue** [xwp/stream#907]
In `Connector_Media`, [the code](https://github.com/xwp/stream/blob/c284f36acc094dd579720f3130e646e097aba9b6/connectors/class-connector-media.php#L140-L141) assumes that if there's a parent ID, the parent post exists. This is not always true if you have an orphaned attachment.

I'd suggest changing the ternary to use `$parent` instead of `$parent_id`

**Comment by kidunot89** [comment]
@rmccue The code doesn't assume that there is a parent. You see if by default `post_parent` is `0` and when passed to `get_post( 0 )` like so it return false. This is all summed up by the ternary operation on the following line. `$parent_id ? $parent->post_title : null;`

**Comment by rmccue** [comment]
@kidunot89 This is for the case where the attachment has a parent ID set, but the parent post does not exist. `get_post( 42 )` can return `null` if the post by that ID does not exist, which causes `$parent->post_title` to cause a fatal error. We've seen this occur in production and crash sites.

(Sidenote: `get_post( 0 )` does *not* return false, instead it uses the globally-set `$post` variable if there is one. In this case, that's benign, but it's still not good practice.)

**Comment by kidunot89** [comment]
🤦🏾‍♂️ my bad, I didn't know. I'll open a PR today.

**Comment by rmccue** [comment]
No worries, and thanks :)

**Comment by kidunot89** [comment]
@rmccue I implemented the patch in an already open PR :point_right: #1154
