### ISSUE TITLE
Declaration of Carbon\Carbon::setTime($hour, $minute, $second = 0) should be compatible with DateTime::setTime($hour, $minute, $second = NULL, $microseconds = NULL)

### ISSUE THREAD

**Issue by ocean90** [xwp/stream#914]
PHP 7.1 changes how Datetime handles microseconds, see http://php.net/manual/de/migration71.incompatible.php#migration71.incompatible.datetime-microseconds.

Looks like this also affects `DateTime::setTime()`which now has a `$microseconds` parameter.

**Comment by mikeyzm** [comment]
Update Carbon library to latest version may solve this problem.

**Comment by Danny-Guzman** [comment]
Carbon::setTime($hour, $minute, $second = NULL) not compatible with
PHP 7.1.0 DateTime::setTime($hour, $minute, $second = null, $microseconds = NULL )

http://php.net/manual/en/datetime.settime.php
7.1.0	The microseconds parameter was added.

On line 681 of the includes/lib/Carbon.php the function setTime is missing the $microseconds = null parameter

**Comment by ahmed-sigmalux** [comment]
Any luck getting your PR committed?

**Comment by Danny-Guzman** [comment]
Negative it always seems to fail the continuous integration, for now I've
just manually made the edits that I needed

**Comment by proweb** [comment]
+1
PHP 7.1

![image](https://user-images.githubusercontent.com/680073/34707441-95c6923c-f51e-11e7-8308-60cd572ce902.png)

**Comment by robertandrews** [comment]
I just switched from PHP 5.6 to 7.2 and found this warning...

`Warning: Declaration of Carbon\Carbon::setTime($hour, $minute, $second = 0) should be compatible with DateTime::setTime($hour, $minute, $second = NULL, $microseconds = NULL) in /home/mysite/public_html/wp-content/plugins/stream/includes/lib/Carbon.php on line 2213`

The same issue also affects the Date Range Filter plugin you worked on.

Any chance of a resolution?

**Comment by DavidCramer** [comment]
Addressed via 4017b31 and #966
