### ISSUE TITLE
Users - no results found

### ISSUE THREAD

**Issue by sammysickweb** [xwp/stream#929]
I'd like to exclude my admin user from the list but the user dropdown shows – no results found. 
![image](https://user-images.githubusercontent.com/30574993/28755297-44673424-750c-11e7-9ce2-277c2eb57701.png)

**Comment by daveglines** [comment]
Bump on this. I'm having the same issue. "No results found" when I select users.

Great plugin though! Looking forward to expanding on it.

**Comment by daveglines** [comment]
Checking in again on this one. Is there a solution? Anyone else have this problem?

**Comment by prowp** [comment]
I am having this problem too. I went through some troubleshooting with it a few weeks ago and discovered a missing nonce from an ajax call that is supposed to fetch users. But now I can't even replicate getting the ajax call to fire (no idea why that is)

**Comment by daveglines** [comment]
We are still having the issue. Continuing to test to see if it's a plugin conflict, but I don't think so. Perhaps the authors will reply at some point?

**Comment by lkraav** [comment]
> We are still having the issue. Continuing to test to see if it's a plugin conflict, but I don't think so. Perhaps the authors will reply at some point?

This plugin has unfortunately been struggling for resources for a lengthy while now. I haven't been able to find out whether there's maybe something clearly better out there and that's where people put their project energy.

**Comment by tareiking** [comment]
@sammysickweb - I know this is a really old issue, but do you know whether you had more than 50 users on your site? 

By default: https://github.com/xwp/stream/blob/develop/classes/class-admin.php#L109 sets a limit of 50 users and is suppose to get initial results via ajax, but my limited testing so far indicates, this is not ajax request is not triggered.

> discovered a missing nonce from an ajax call that is supposed to fetch users.

@prowp - I also fail the nonce check and couldn't see this ever being output in the stream plugin :)

**Comment by daveglines** [comment]
Definitely more than 50 users. We have 1600+ users on our site. Would
really like this fixed if possible. Still does not work for us.

DG
