### ISSUE TITLE
Stream not capturing SSO sign-ins from OneLogin

### ISSUE THREAD

**Issue by aeromusek** [xwp/stream#946]
We use the [OneLogin plugin](https://wordpress.org/plugins/onelogin-saml-sso/) for authentication on our site, and Stream is not capturing user log in events. These events are recorded perfectly on clones of the site that use the standard WordPress authentication.

Happy to help dig up logs or other necessary data for testing.

**Comment by kidunot89** [comment]
@aeromusek Can we confirm that this is still an issue?
