### ISSUE TITLE
Backward compatibility - Call to undefined function WP_Stream\wp_add_inline_script()

### ISSUE THREAD

**Issue by logichub** [xwp/stream#948]
I am unable to access Stream admin page after updating it from 3.0.7 to 3.2.2. I see a blank page when I try to access the Stream admin page. debug.log file contains following error:

`Call to undefined function WP_Stream\wp_add_inline_script() in /wp-content/plugins/stream/alerts/class-alert-type-highlight.php on line 277`

- WordPress 4.3.1
- Stream 3.2.2

**Comment by cfoellmann** [comment]
@logichub @DavidCramer too bad that there was no response. Maybe close for now?
