### ISSUE TITLE
count_users() is called for every user role on the settings screen.

### ISSUE THREAD

**Issue by johnbillion** [xwp/stream#949]
On the Stream Settings screen, `count_users()` is unnecessarily called once for every role on the site, instead of just once. Calling `count_users()` is expensive, and gets slower the more users and roles there are on a site.

Ref: https://github.com/xwp/stream/blob/06316e9cc295429ae4ab7c550cddce898919e650/classes/class-settings.php#L821-L826

This call to `count_users()` should be moved outside of the `foreach()` loop so it's only called once.

**Comment by DavidCramer** [comment]
adressed via #964
