### ISSUE TITLE
PHP Warning:  A non-numeric value encountered in /stream/classes/class-settings.php on line 928

### ISSUE THREAD

**Issue by ahmed-sigmalux** [xwp/stream#952]
I'm seeing the following warning in debug.log:

`PHP Warning:  A non-numeric value encountered in /var/www/wordpress/wp-content/plugins/stream/classes/class-settings.php on line 928`

**Comment by lkraav** [comment]
Sounds like PHP 7.1 compatibility thing, I started seeing this warning after upgrade.
