### ISSUE TITLE
Add filter for 'settings_cap'

### ISSUE THREAD

**Issue by cfoellmann** [xwp/stream#953]
I would like to filter in the Admin class
```php
        /**
	 * Capability name for viewing settings
	 *
	 * @var string
	 */
	public $settings_cap = 'manage_options';
```
to prevent on multisite the site admins to change settings for the blog (subsite). I don't want my users to have access to the "not recommended" settings.

Maybe in `Admin\_construct()`
`$this->settings_cap = apply_filters( 'wp_stream_settings_cap', 'manage_options' );`

**Comment by DavidCramer** [comment]
@cfoellmann - Sorry for the late response. 
If this is still relevant, you can simply alter the `$settings_cap` in an `init` hook since it's public.
```php
add_action('init', function(){
	wp_stream_get_instance()->admin->settings_cap = 'my_super_cap';
}, 9 ); // Admin is activated in init at priority 10.
```
