### ISSUE TITLE
CRON check is incorrect

### ISSUE THREAD

**Issue by khromov** [xwp/stream#959]
Before showing the "WP Cron Tracking" option in the admin, Stream checks if `DISABLE_WP_CRON` is not true.

I don't think this is a correct condition to check. `DISABLE_WP_CRON` doesn't actually disable CRON, it just stops it from running during normal requests. CRON still runs when manually loading `/wp-cron.php`. 

The check should be removed, as WP CRON can never be truly disabled.

**Comment by DavidCramer** [comment]
@khromov Having thought this through, I believe that how it is now is in fact the correct way to do it.
When you define `DISABLE_WP_CRON`, you are telling WordPress to not use [`spawn_cron()`](https://core.trac.wordpress.org/browser/tags/4.9/src/wp-includes/cron.php#L371)

The `wp-cron.php` file you mention is the file used when you want to control the cron manually via your own method, as indicated in the files header in [`wp-cron.php`](https://core.trac.wordpress.org/browser/tags/4.9.5/src/wp-cron.php) :

> Defining DISABLE_WP_CRON as true and calling this file directly are
mutually exclusive and the latter does not rely on the former to work.

**Comment by kasparsd** [comment]
I think the option to track cron events shouldn't be tied to the state of `DISABLE_WP_CRON` since that applies to the front-end CRON feature only and not cron jobs in general.

**Comment by kasparsd** [comment]
Version 3.4.1 has been released, thanks for reporting the issue @khromov!
