### ISSUE TITLE
Regular expressions leaking into log entries

### ISSUE THREAD

**Issue by khromov** [xwp/stream#960]
We've had some very strange log entries recently where part of the regular expression Stream uses to parse entries somehow gets included as part of the log entry. Here is a screenshot:

![screen shot 2018-01-11 at 18 15 05](https://user-images.githubusercontent.com/1207507/34837657-bff7a134-f6fb-11e7-91ee-bfdb08c7c1d2.png)

Unfortunately, we have not been able to reproduce what causes this behaviour.

**Comment by DavidCramer** [comment]
@khromov , those look more like the rewrite rules that got updated. Do you have any plugins that manage rewrite rules or permalinks?

**Comment by khromov** [comment]
@DavidCramer Ah, you are right! I don't recall us running any plugins that manage rewrite rules or permalinks, but we might have changed the permalink settings at some point which should trigger a rebuild. 

The confusing part is why the message is worded in a way that suggests that the content of the permalink settings is the settings key. Shouldn't it just say something like `"rewrite_rules" setting was updated"`?

**Comment by DavidCramer** [comment]
@khromov It does when using the permalinks settings page. Which is why this is possibly been done via a permalink/rewrite rules plugin.

Anyway, glad it's identified as not a regex leak.
