### ISSUE TITLE
Use a unique nonce for the Reset Stream Database functionality

### ISSUE THREAD

**Issue by johnbillion** [xwp/stream#971]
This is a follow-up to #945.

The nonce that's used for the Reset Stream Database functionality is the same as the nonce used for the Uninstall link on the Plugins listing screen.

This means that even if the Reset Stream Database functionality settings screen field is removed, it's still possible for a rogue user to trigger the database reset by manually calling `admin-ajax.php?action=wp_stream_reset&wp_stream_nonce=<nonce>`, where the nonce value is copied from the Uninstall link on the Plugins screen.

The Reset Stream Database functionality and the Uninstall functionality shouldn't used the same nonce.

**Comment by DavidCramer** [comment]
@johnbillion , good catch. I'll try address that issue. Thanks!
