### ISSUE TITLE
GDPR: Privacy education

### ISSUE THREAD

**Issue by lukecarbis** [xwp/stream#980]
- Stream should notify users of new privacy settings after updating.
- Stream should publish a "privacy statement" that could be added a websites privacy policy
- Stream should publish video walkthroughs of how to comply with a GDPR export or deletion request

**Comment by tobutridaz** [comment]
> Stream should notify users of new privacy settings after updating.

Are we sure that Stream should only notify users of a new privacy setting? After all, stream is collecting personal data (IP, username). GDPR states 

> Consent of the Data Subject means any freely given, specific, informed and unambiguous indication of the Data Subject's wishes by which he/she, by a statement or by a clear **affirmative** action, signifies agreement to processing of the Personal Data relating to him or her.

Shouldn't we be asking the users to optin to them being "tracked" by Stream?

**Comment by lukecarbis** [comment]
@tobutridaz We want to give those opt-in tools to the site admin. Stream is often used by (for example) an Australian agency, who wants to keep track of the admin actions taken by their developer and client (both also in Australia). GDPR should only applies if their are users in the EU with admin access.

**Comment by tobutridaz** [comment]
If this will be as an option for the site admin, then great - that works!
