### ISSUE TITLE
Programmatically exclude (filter)

### ISSUE THREAD

**Issue by cfoellmann** [xwp/stream#985]
Is there a way to programmatically add an exclude rule?

My case: I use the `snitch` plugin to capture wp remote connections but it floods stream. It is writing to a CPT so I can exclude but I would love to contribute a filter to snitch or stream to keep snitch out of the log automatically.

**Comment by staude** [comment]
Hi Christian,

the filter is wp_stream_posts_exclude_post_types

At the Pluginkollektiv Hackathon ( https://works.pluginkollektiv.org )   currently I am working on https://github.com/pluginkollektiv/snitch/issues/21 :)
