### ISSUE TITLE
Wiki: `Connector` class constructor takes 0 parameters, drop example `$stream->log` parameter

### ISSUE THREAD

**Issue by lkraav** [xwp/stream#991]
https://github.com/xwp/stream/wiki/Creating-a-Custom-Connector#registering-a-connector

`$class = new $class_name( $stream->log );` will get flagged in advanced IDEs like PHPStorm, as method call w/ 1 parameter, where method signature has 0 parameters.

Better: `$class = $class_name();`

**Comment by kidunot89** [comment]
[Fixed](wp_stream_get_iso_8601_extended_date)

**Comment by lkraav** [comment]
:+1: 

Is "Fixed" link above supposed to link somewhere other than an empty search result?

**Comment by kidunot89** [comment]
@lkraav My bad it wasn't suppose to be a link :sweat_smile:
